/**
 * ACT I — INCIDENT DETECTION.
 *
 * Every figure is a `{fact}` placeholder or a `fact:` reference, resolved
 * from the Stage 3–5 artefacts at run time (facts.js). Offsets are in
 * milliseconds of briefing time; the director scales them with speed.
 */

import { RUNS, defineScene } from '../timeline.js';

const ALL = [RUNS.THREE, RUNS.SIX, RUNS.FULL];
const SIX_FULL = [RUNS.SIX, RUNS.FULL];

const USGS = { source: 'USGS', cls: 'OBSERVED' };
const SHAKEMAP = {
  source: 'USGS SHAKEMAP · MODELLED INTENSITY',
  cls: 'OBSERVED',
};

export const INCOMING = defineScene({
  id: 'incoming',
  number: 1,
  act: 'I',
  title: 'Incoming incident',
  question: 'What has happened?',
  explore: 0,
  runs: ALL,
  setup: [
    { type: 'veil', opacity: 0.94 },
    { type: 'layer.show', layer: 'graticule' },
    {
      type: 'camera.fly',
      to: { lon: 40, lat: 18 },
      rangeKm: 21000,
      pitch: -90,
    },
  ],
  beats: [
    {
      id: 'detected',
      caption:
        'INCIDENT DETECTED · {quake.time|dateShort} · {quake.time|utcHM}',
      narration:
        '{quake.time|dateLong}. {quake.time|utcHM}. A major earthquake is detected in South Asia.',
      minHoldMs: 600,
      actions: [
        { at: 0, type: 'audio.cue', cue: 'tick' },
        {
          at: 0,
          type: 'title.type',
          id: 'title',
          duration: 2600,
          screen: { x: 0.07, y: 0.32 },
          lines: [
            { text: 'NATURAL DISASTER INTELLIGENCE', className: 'is-kicker' },
            { text: 'INCIDENT DETECTED', className: 'is-alert' },
            { text: '{quake.time|dateShort}' },
            { text: '{quake.time|utcHM}' },
          ],
        },
        { at: 400, type: 'veil', opacity: 0.8, duration: 2400 },
        { at: 2800, type: 'audio.cue', cue: 'reveal' },
      ],
    },
    {
      id: 'locating',
      caption: 'LOCATING THE EVENT',
      narration: 'Locating the event.',
      minHoldMs: 400,
      actions: [
        {
          at: 0,
          type: 'annotation.draw',
          kind: 'typed',
          id: 'locating',
          duration: 900,
          screen: { x: 0.07, y: 0.56 },
          className: 'brf-typed brf-typed--status',
          lines: ['LOCATING EVENT …'],
        },
        { at: 200, type: 'veil', opacity: 0.3, duration: 3000 },
        { at: 1600, type: 'annotation.remove', id: 'title' },
        {
          at: 300,
          type: 'camera.fly',
          to: 'epicentre',
          rangeKm: 7500,
          pitch: -90,
          duration: 3600,
        },
        {
          at: 2600,
          type: 'annotation.draw',
          kind: 'bracket',
          id: 'find',
          anchor: 'epicentre',
          size: 150,
          duration: 900,
        },
      ],
    },
  ],
});

export const LOCATE = defineScene({
  id: 'locate',
  number: 2,
  act: 'I',
  title: 'Locate Nepal',
  question: 'Where on Earth is this?',
  explore: 1,
  runs: ALL,
  setup: [
    { type: 'veil', opacity: 0.3 },
    { type: 'camera.fly', to: 'epicentre', rangeKm: 7500, pitch: -90 },
  ],
  beats: [
    {
      id: 'south-asia',
      caption: 'SOUTH ASIA · THE CENTRAL HIMALAYA',
      narration:
        'The event is in the central Himalaya, between India and China.',
      runs: SIX_FULL,
      minHoldMs: 300,
      actions: [
        { at: 0, type: 'veil', opacity: 0.12, duration: 2500 },
        {
          at: 0,
          type: 'camera.fly',
          to: 'nepal',
          rangeKm: 2700,
          pitch: -82,
          duration: 3400,
        },
        {
          at: 500,
          type: 'annotation.draw',
          kind: 'label',
          id: 'india',
          anchor: 'india',
          text: 'INDIA',
          size: 'country',
        },
        {
          at: 900,
          type: 'annotation.draw',
          kind: 'label',
          id: 'china',
          anchor: 'china',
          text: 'CHINA',
          size: 'country',
        },
      ],
    },
    {
      id: 'border',
      caption: 'NEPAL',
      narration:
        'This is Nepal. Its border runs the length of the central Himalaya.',
      minHoldMs: 500,
      actions: [
        { at: 0, type: 'layer.show', layer: 'outline', duration: 3200 },
        { at: 0, type: 'audio.cue', cue: 'trace' },
        {
          at: 400,
          type: 'layer.show',
          layer: 'mask',
          alpha: 0.6,
          duration: 1600,
        },
        { at: 1200, type: 'annotation.remove', id: 'india' },
        { at: 1200, type: 'annotation.remove', id: 'china' },
        {
          at: 2900,
          type: 'annotation.draw',
          kind: 'callout',
          id: 'nepal-callout',
          anchor: 'nepal',
          title: 'NEPAL',
          lines: [
            'HIMALAYAN REGION',
            '{geo.districtCount|int} DISTRICTS IN 2015',
          ],
          tag: { source: 'OCHA COD-AB', cls: 'OFFICIAL' },
          dx: 170,
          dy: -120,
          duration: 1000,
        },
        { at: 3000, type: 'audio.cue', cue: 'reveal' },
      ],
    },
    {
      id: 'epicentre',
      caption:
        'KATHMANDU · AND THE EPICENTRE, IN {geo.epicentreDistrict|upper}',
      narration:
        'The capital, Kathmandu, sits in a valley here. The rupture began to the north-west, in {geo.epicentreDistrict} district.',
      minHoldMs: 300,
      actions: [
        {
          at: 0,
          type: 'annotation.draw',
          kind: 'label',
          id: 'ktm',
          anchor: 'kathmandu',
          text: 'KATHMANDU',
          size: 'city',
          dx: 44,
          dy: -22,
        },
        {
          at: 0,
          type: 'annotation.draw',
          kind: 'bracket',
          id: 'ktm-bracket',
          anchor: 'kathmandu',
          size: 46,
        },
        { at: 1200, type: 'annotation.remove', id: 'nepal-callout' },
        {
          at: 1500,
          type: 'annotation.draw',
          kind: 'pulse',
          id: 'epi-pulse',
          anchor: 'epicentre',
          colour: '#ff5a5f',
          maxPx: 60,
        },
        { at: 1500, type: 'audio.cue', cue: 'pulse' },
        {
          at: 1900,
          type: 'annotation.draw',
          kind: 'callout',
          id: 'epi-callout',
          anchor: 'epicentre',
          title: 'EPICENTRE · {geo.epicentreDistrict|upper}',
          lines: ['{quake.place|upper}'],
          tag: USGS,
          dx: -210,
          dy: -90,
        },
        {
          at: 3700,
          type: 'camera.fly',
          to: 'epicentre',
          rangeKm: 900,
          pitch: -68,
          duration: 3200,
        },
      ],
    },
  ],
});

export const MAIN_SHOCK = defineScene({
  id: 'main-shock',
  number: 4,
  act: 'I',
  title: 'Main shock',
  question: 'How big was it, and how deep?',
  explore: 2,
  runs: ALL,
  keep: ['outline', 'mask', 'epi-pulse', 'ktm'],
  setup: [
    { type: 'veil', opacity: 0.12 },
    { type: 'layer.show', layer: 'outline' },
    { type: 'layer.show', layer: 'mask', alpha: 0.6 },
    {
      type: 'annotation.draw',
      kind: 'pulse',
      id: 'epi-pulse',
      anchor: 'epicentre',
      colour: '#ff5a5f',
      maxPx: 60,
    },
    {
      type: 'annotation.draw',
      kind: 'label',
      id: 'ktm',
      anchor: 'kathmandu',
      text: 'KATHMANDU',
      size: 'city',
      dx: 44,
      dy: -22,
    },
    { type: 'camera.fly', to: 'epicentre', rangeKm: 900, pitch: -68 },
  ],
  beats: [
    {
      id: 'magnitude',
      caption: 'MAGNITUDE {quake.magnitude|dec1}',
      narration: 'Magnitude {quake.magnitude|dec1}.',
      minHoldMs: 600,
      actions: [
        {
          at: 0,
          type: 'camera.fly',
          to: 'epicentre',
          rangeKm: 520,
          pitch: -58,
          heading: 12,
          duration: 2600,
        },
        { at: 0, type: 'audio.cue', cue: 'hit' },
        {
          at: 0,
          type: 'annotation.draw',
          kind: 'pulse',
          id: 'epi-pulse',
          anchor: 'epicentre',
          colour: '#ff5a5f',
          maxPx: 140,
          count: 4,
        },
        {
          at: 500,
          type: 'metric.count',
          id: 'magnitude',
          fact: 'quake.magnitude',
          format: 'dec1',
          label: 'MOMENT MAGNITUDE (MW)',
          anchor: 'epicentre',
          size: 'xl',
          dx: 44,
          dy: -70,
          duration: 1700,
        },
      ],
    },
    {
      id: 'depth',
      caption: 'FOCAL DEPTH {quake.depthKm|dec1} KM · {quake.time|utcTime}',
      narration:
        'Its focus was {quake.depthKm|dec1} kilometres deep. The energy was released close to the surface.',
      minHoldMs: 700,
      actions: [
        {
          at: 0,
          type: 'metric.count',
          id: 'depth',
          fact: 'quake.depthKm',
          format: 'dec1',
          label: 'KM FOCAL DEPTH',
          anchor: 'epicentre',
          size: 'lg',
          dx: 44,
          dy: 36,
          duration: 1400,
        },
        {
          at: 900,
          type: 'annotation.draw',
          kind: 'typed',
          id: 'time',
          duration: 1100,
          screen: { x: 0.66, y: 0.18 },
          className: 'brf-typed brf-typed--data',
          lines: [
            'ORIGIN TIME',
            '{quake.time|utcTime}',
            '{quake.time|dateShort}',
            'USGS {quake.id|upper}',
          ],
        },
        {
          at: 2400,
          type: 'annotation.draw',
          kind: 'callout',
          id: 'shallow',
          anchor: 'epicentre',
          title: 'SHALLOW',
          lines: ['ENERGY RELEASED CLOSE TO THE SURFACE'],
          tag: USGS,
          dx: -240,
          dy: 70,
        },
      ],
    },
  ],
});

export const SHAKING = defineScene({
  id: 'shaking',
  number: 5,
  act: 'I',
  title: 'Shaking expands',
  question: 'Where did the ground shake, and how hard?',
  explore: 4,
  runs: ALL,
  keep: ['outline', 'mask', 'epi-pulse', 'ktm'],
  setup: [
    { type: 'veil', opacity: 0.12 },
    { type: 'layer.show', layer: 'outline' },
    { type: 'layer.show', layer: 'mask', alpha: 0.6 },
    {
      type: 'annotation.draw',
      kind: 'pulse',
      id: 'epi-pulse',
      anchor: 'epicentre',
      colour: '#ff5a5f',
      maxPx: 60,
    },
    {
      type: 'annotation.draw',
      kind: 'label',
      id: 'ktm',
      anchor: 'kathmandu',
      text: 'KATHMANDU',
      size: 'city',
      dx: 44,
      dy: -22,
    },
    {
      type: 'camera.fly',
      to: 'epicentre',
      rangeKm: 520,
      pitch: -58,
      heading: 12,
    },
  ],
  beats: [
    {
      id: 'spread',
      caption: 'THE SHAKING SPREADS EAST ALONG THE MOUNTAINS',
      narration: 'Within seconds, the shaking spread east along the mountains.',
      minHoldMs: 400,
      actions: [
        {
          at: 0,
          type: 'camera.fly',
          to: 'shakeCentre',
          rangeKm: 1150,
          pitch: -72,
          heading: 0,
          duration: 3200,
        },
        { at: 300, type: 'layer.show', layer: 'bands', duration: 5200 },
        { at: 300, type: 'audio.cue', cue: 'trace' },
      ],
    },
    {
      id: 'scale',
      caption: 'MODELLED INTENSITY · VI STRONG · VII VERY STRONG · VIII SEVERE',
      narration:
        'The intensity is modelled on the Mercalli scale. Six is strong, seven very strong, eight severe.',
      runs: SIX_FULL,
      minHoldMs: 400,
      actions: [
        {
          at: 0,
          type: 'chart.enter',
          chart: 'mmiLegend',
          id: 'mmi-legend',
          screen: { x: 0.03, y: 0.5 },
        },
        { at: 200, type: 'chart.update', id: 'mmi-legend', op: 'revealAll' },
        { at: 1600, type: 'layer.filter', layer: 'bands', highlight: 7 },
        {
          at: 1600,
          type: 'chart.update',
          id: 'mmi-legend',
          op: 'focus',
          index: 2,
        },
        { at: 3800, type: 'layer.filter', layer: 'bands', highlight: null },
        {
          at: 3800,
          type: 'chart.update',
          id: 'mmi-legend',
          op: 'focus',
          index: null,
        },
      ],
    },
    {
      id: 'kathmandu',
      caption:
        'KATHMANDU: MMI {exposure.kathmandu.maxMmi|dec1} · {exposure.kathmandu.exposed|mega2} PEOPLE INSIDE MMI VI+',
      narration:
        'It reached the Kathmandu Valley at intensity {exposure.kathmandu.maxMmi|dec1}. {exposure.kathmandu.exposedPercent|int} percent of the district’s {exposure.kathmandu.exposed|millionWords} modelled residents were inside intensity six or stronger.',
      minHoldMs: 800,
      actions: [
        {
          at: 0,
          type: 'annotation.draw',
          kind: 'bracket',
          id: 'ktm-bracket',
          anchor: 'kathmandu',
          size: 64,
        },
        {
          at: 300,
          type: 'camera.fly',
          to: 'kathmandu',
          rangeKm: 720,
          pitch: -66,
          heading: -8,
          duration: 3000,
        },
        {
          at: 700,
          type: 'metric.count',
          id: 'ktm-people',
          fact: 'exposure.kathmandu',
          key: 'exposed',
          format: 'mega2',
          label: 'MODELLED RESIDENTS · KATHMANDU · INSIDE MMI VI+',
          anchor: 'kathmandu',
          size: 'lg',
          dx: 56,
          dy: 50,
          duration: 1800,
          tag: { source: 'WORLDPOP × USGS SHAKEMAP', cls: 'DERIVED' },
        },
        {
          at: 3000,
          type: 'annotation.draw',
          kind: 'callout',
          id: 'ktm-mmi',
          anchor: 'kathmandu',
          title: 'PEAK MMI {exposure.kathmandu.maxMmi|dec1}',
          lines: ['DISTRICT PEAK · MODELLED'],
          tag: SHAKEMAP,
          dx: -230,
          dy: -80,
        },
        { at: 3100, type: 'audio.cue', cue: 'reveal' },
      ],
    },
  ],
});

const MODEL_FIT = { source: 'USGS · OMORI FIT', cls: 'MODEL FIT' };

/* The sequence scenes share one frame: the rupture zone, epicentre to Kathmandu and east. */
const sequenceBase = [
  { type: 'veil', opacity: 0.12 },
  { type: 'layer.show', layer: 'outline' },
  { type: 'layer.show', layer: 'mask', alpha: 0.6 },
  {
    type: 'annotation.draw',
    kind: 'pulse',
    id: 'epi-pulse',
    anchor: 'epicentre',
    colour: '#ff5a5f',
    maxPx: 50,
  },
  {
    type: 'annotation.draw',
    kind: 'label',
    id: 'ktm',
    anchor: 'kathmandu',
    text: 'KATHMANDU',
    size: 'city',
    dx: 44,
    dy: -22,
  },
];

export const FIRST_HOURS = defineScene({
  id: 'first-hours',
  number: 6,
  act: 'I',
  title: 'First hours',
  question: 'What happened after the main shock?',
  explore: 3,
  runs: SIX_FULL,
  keep: ['outline', 'mask', 'epi-pulse', 'ktm'],
  setup: [
    ...sequenceBase,
    {
      type: 'camera.fly',
      to: 'shakeCentre',
      rangeKm: 640,
      pitch: -68,
      heading: 0,
    },
  ],
  beats: [
    {
      id: 'first-hour',
      caption: 'THE FIRST HOUR: {seq.hourly.0.count|int} MORE EARTHQUAKES',
      narration:
        'The ground did not settle. In the first hour alone, {seq.hourly.0.count|int} more earthquakes were recorded.',
      minHoldMs: 400,
      actions: [
        { at: 0, type: 'layer.show', layer: 'events', hour: 0 },
        {
          at: 0,
          type: 'timeline.seek',
          layer: 'events',
          toHour: 1,
          duration: 3200,
        },
        { at: 0, type: 'audio.cue', cue: 'pulse' },
        {
          at: 300,
          type: 'camera.fly',
          to: 'epicentre',
          rangeKm: 420,
          pitch: -62,
          heading: 6,
          duration: 4200,
        },
        {
          at: 900,
          type: 'metric.count',
          id: 'hour-count',
          fact: 'seq.hourly',
          key: 0,
          subKey: 'count',
          format: 'int',
          label: 'EARTHQUAKES IN THE FIRST HOUR',
          screen: { x: 0.64, y: 0.18 },
          size: 'xl',
          duration: 1800,
          tag: USGS,
        },
      ],
    },
    {
      id: 'first-day',
      caption:
        '{seq.firstDay|int} IN THE FIRST DAY · SPREADING EAST ALONG THE RUPTURE',
      narration:
        'By the end of the first day there were {seq.firstDay|int}, and they had spread east from the epicentre, toward Kathmandu and beyond.',
      minHoldMs: 500,
      actions: [
        {
          at: 0,
          type: 'timeline.seek',
          layer: 'events',
          toHour: 24,
          duration: 6000,
        },
        { at: 0, type: 'annotation.remove', id: 'hour-count' },
        {
          at: 200,
          type: 'camera.fly',
          to: 'shakeCentre',
          rangeKm: 600,
          pitch: -66,
          heading: 10,
          duration: 6200,
        },
        {
          at: 600,
          type: 'metric.count',
          id: 'day-count',
          fact: 'seq.firstDay',
          format: 'int',
          label: 'EARTHQUAKES IN THE FIRST DAY',
          screen: { x: 0.64, y: 0.18 },
          size: 'xl',
          duration: 5200,
          tag: USGS,
        },
        {
          at: 4600,
          type: 'annotation.draw',
          kind: 'callout',
          id: 'extent',
          anchor: 'secondary',
          title: 'AFTERSHOCK ZONE',
          lines: ['{seq.extentKm|int} KM EAST TO WEST'],
          tag: USGS,
          dx: 120,
          dy: -90,
        },
      ],
    },
    {
      id: 'first-week',
      caption: '{seq.firstWeek|int} IN THE FIRST WEEK',
      narration: 'By the end of the first week, {seq.firstWeek|int}.',
      runs: [RUNS.FULL],
      minHoldMs: 500,
      actions: [
        {
          at: 0,
          type: 'timeline.seek',
          layer: 'events',
          toHour: 168,
          duration: 4000,
        },
        { at: 0, type: 'annotation.remove', id: 'day-count' },
        {
          at: 400,
          type: 'metric.count',
          id: 'week-count',
          fact: 'seq.firstWeek',
          format: 'int',
          label: 'EARTHQUAKES IN THE FIRST WEEK',
          screen: { x: 0.64, y: 0.18 },
          size: 'xl',
          duration: 3400,
          tag: USGS,
        },
      ],
    },
  ],
});

export const SECOND_SHOCK = defineScene({
  id: 'second-shock',
  number: 8,
  act: 'I',
  title: 'Second major shock',
  question: 'Was it over?',
  explore: 3,
  runs: SIX_FULL,
  keep: ['outline', 'mask', 'epi-pulse', 'ktm', 'events'],
  setup: [
    ...sequenceBase,
    { type: 'layer.show', layer: 'events', hour: 168 },
    { type: 'timeline.seek', layer: 'events', toHour: 168 },
    {
      type: 'camera.fly',
      to: 'shakeCentre',
      rangeKm: 600,
      pitch: -66,
      heading: 10,
    },
  ],
  beats: [
    {
      id: 'second',
      caption:
        '{seq.secondary.daysFromMainShock|int} DAYS LATER · MAGNITUDE {seq.secondary.magnitude|dec1}',
      narration:
        '{seq.secondary.daysFromMainShock|int} days later, a second major earthquake: magnitude {seq.secondary.magnitude|dec1}, east of the first.',
      minHoldMs: 500,
      actions: [
        {
          at: 0,
          type: 'timeline.seek',
          layer: 'events',
          toHour: { fact: 'seq.largest', path: [1, 'hoursFromMainShock'] },
          duration: 2600,
        },
        { at: 0, type: 'annotation.remove', id: 'week-count' },
        { at: 0, type: 'annotation.remove', id: 'extent' },
        {
          at: 300,
          type: 'camera.fly',
          to: 'secondary',
          rangeKm: 380,
          pitch: -60,
          heading: -6,
          duration: 3600,
        },
        {
          at: 2600,
          type: 'annotation.draw',
          kind: 'pulse',
          id: 'second-pulse',
          anchor: 'secondary',
          colour: '#ffb020',
          maxPx: 120,
          count: 4,
        },
        { at: 2600, type: 'audio.cue', cue: 'hit' },
        {
          at: 3000,
          type: 'metric.count',
          id: 'second-mag',
          fact: 'seq.secondary',
          key: 'magnitude',
          format: 'dec1',
          label: 'MOMENT MAGNITUDE · {seq.secondary.time|dateShort}',
          anchor: 'secondary',
          size: 'xl',
          dx: 44,
          dy: -70,
          duration: 1500,
          tag: USGS,
        },
        {
          at: 4400,
          type: 'annotation.draw',
          kind: 'callout',
          id: 'second-where',
          anchor: 'secondary',
          title:
            '{seq.largest.1.distanceFromEpicentreKm|int} KM EAST OF THE FIRST',
          lines: [
            '{seq.secondary.time|utcHM} · {seq.secondary.time|dateShort}',
          ],
          tag: USGS,
          dx: -250,
          dy: 60,
        },
      ],
    },
    {
      id: 'decay',
      caption:
        'IT RESET THE DECAY · p {omori.before.pValue|dec2} BEFORE, {omori.after.pValue|dec2} AFTER',
      narration:
        'It reset the sequence. Before it, the aftershocks faded at the rate the Omori law describes. After it, they faded far more slowly, and the law fits them poorly.',
      runs: [RUNS.FULL],
      minHoldMs: 700,
      actions: [
        {
          at: 0,
          type: 'timeline.seek',
          layer: 'events',
          toHour: 2200,
          duration: 6500,
        },
        { at: 0, type: 'annotation.remove', id: 'second-where' },
        {
          at: 200,
          type: 'camera.fly',
          to: 'shakeCentre',
          rangeKm: 620,
          pitch: -68,
          heading: 0,
          duration: 4800,
        },
        {
          at: 700,
          type: 'annotation.draw',
          kind: 'typed',
          id: 'omori',
          duration: 1800,
          screen: { x: 0.62, y: 0.16 },
          className: 'brf-typed brf-typed--data',
          lines: [
            'AFTERSHOCK DECAY · OMORI LAW',
            'BEFORE: p = {omori.before.pValue|dec2} · R² {omori.before.rSquared|dec2}',
            'AFTER: p = {omori.after.pValue|dec2} · R² {omori.after.rSquared|dec2}',
            'A WEAK FIT IS REPORTED AS ONE',
          ],
          tag: MODEL_FIT,
        },
        { at: 5600, type: 'annotation.remove', id: 'second-mag' },
      ],
    },
  ],
});

export const ACT1 = Object.freeze([
  INCOMING,
  LOCATE,
  MAIN_SHOCK,
  SHAKING,
  FIRST_HOURS,
  SECOND_SHOCK,
]);
