/**
 * UN Comtrade area code tables.
 *
 * Comtrade identifies countries by UN M49 numeric code, and the public preview
 * endpoint returns `reporterISO`, `partnerISO` and `reporterDesc` as NULL
 * (measured; see docs/DATA_AVAILABILITY_MATRIX.md §1.1). Codes must therefore be
 * resolved locally, which is what this table is for.
 *
 * GENERATED FILE. Regenerate with `node scripts/build-comtrade-codes.mjs`.
 *
 * Source:    UN Comtrade reference files, retrieved 2026-09-16
 *            https://comtradeapi.un.org/files/v1/app/reference/Reporters.json
 *            https://comtradeapi.un.org/files/v1/app/reference/partnerAreas.json
 * Licence:   UN Comtrade terms of use
 *
 * Portable: no Cesium, no Node, no browser globals.
 */

/** Areas that report their own trade to Comtrade. */
export const REPORTERS = Object.freeze([
  { code: 4, iso3: 'AFG', name: 'Afghanistan' },
  { code: 8, iso3: 'ALB', name: 'Albania' },
  { code: 12, iso3: 'DZA', name: 'Algeria' },
  { code: 20, iso3: 'AND', name: 'Andorra' },
  { code: 24, iso3: 'AGO', name: 'Angola' },
  { code: 28, iso3: 'ATG', name: 'Antigua and Barbuda' },
  { code: 31, iso3: 'AZE', name: 'Azerbaijan' },
  { code: 32, iso3: 'ARG', name: 'Argentina' },
  { code: 36, iso3: 'AUS', name: 'Australia' },
  { code: 40, iso3: 'AUT', name: 'Austria' },
  { code: 44, iso3: 'BHS', name: 'Bahamas' },
  { code: 48, iso3: 'BHR', name: 'Bahrain' },
  { code: 50, iso3: 'BGD', name: 'Bangladesh' },
  { code: 51, iso3: 'ARM', name: 'Armenia' },
  { code: 52, iso3: 'BRB', name: 'Barbados' },
  { code: 56, iso3: 'BEL', name: 'Belgium' },
  { code: 58, iso3: 'BEL', name: 'Belgium-Luxembourg (...1998)' },
  { code: 60, iso3: 'BMU', name: 'Bermuda' },
  { code: 64, iso3: 'BTN', name: 'Bhutan' },
  { code: 68, iso3: 'BOL', name: 'Bolivia (Plurinational State of)' },
  { code: 70, iso3: 'BIH', name: 'Bosnia Herzegovina' },
  { code: 72, iso3: 'BWA', name: 'Botswana' },
  { code: 76, iso3: 'BRA', name: 'Brazil' },
  { code: 84, iso3: 'BLZ', name: 'Belize' },
  { code: 90, iso3: 'SLB', name: 'Solomon Isds' },
  { code: 92, iso3: 'VGB', name: 'Br. Virgin Isds' },
  { code: 96, iso3: 'BRN', name: 'Brunei Darussalam' },
  { code: 100, iso3: 'BGR', name: 'Bulgaria' },
  { code: 104, iso3: 'MMR', name: 'Myanmar' },
  { code: 108, iso3: 'BDI', name: 'Burundi' },
  { code: 112, iso3: 'BLR', name: 'Belarus' },
  { code: 116, iso3: 'KHM', name: 'Cambodia' },
  { code: 120, iso3: 'CMR', name: 'Cameroon' },
  { code: 124, iso3: 'CAN', name: 'Canada' },
  { code: 132, iso3: 'CPV', name: 'Cabo Verde' },
  { code: 136, iso3: 'CYM', name: 'Cayman Isds' },
  { code: 140, iso3: 'CAF', name: 'Central African Rep.' },
  { code: 144, iso3: 'LKA', name: 'Sri Lanka' },
  { code: 148, iso3: 'TCD', name: 'Chad' },
  { code: 152, iso3: 'CHL', name: 'Chile' },
  { code: 156, iso3: 'CHN', name: 'China' },
  { code: 170, iso3: 'COL', name: 'Colombia' },
  { code: 174, iso3: 'COM', name: 'Comoros' },
  { code: 175, iso3: 'MYT', name: 'Mayotte (Overseas France)' },
  { code: 178, iso3: 'COG', name: 'Congo' },
  { code: 180, iso3: 'COD', name: 'Dem. Rep. of the Congo' },
  { code: 184, iso3: 'COK', name: 'Cook Isds' },
  { code: 188, iso3: 'CRI', name: 'Costa Rica' },
  { code: 191, iso3: 'HRV', name: 'Croatia' },
  { code: 192, iso3: 'CUB', name: 'Cuba' },
  { code: 196, iso3: 'CYP', name: 'Cyprus' },
  { code: 200, iso3: 'CSK', name: 'Czechoslovakia (...1992)' },
  { code: 203, iso3: 'CZE', name: 'Czechia' },
  { code: 204, iso3: 'BEN', name: 'Benin' },
  { code: 208, iso3: 'DNK', name: 'Denmark' },
  { code: 212, iso3: 'DMA', name: 'Dominica' },
  { code: 214, iso3: 'DOM', name: 'Dominican Rep.' },
  { code: 218, iso3: 'ECU', name: 'Ecuador' },
  { code: 222, iso3: 'SLV', name: 'El Salvador' },
  { code: 226, iso3: 'GNQ', name: 'Equatorial Guinea' },
  { code: 230, iso3: 'ETH', name: 'Ethiopia (...1992)' },
  { code: 231, iso3: 'ETH', name: 'Ethiopia' },
  { code: 232, iso3: 'ERI', name: 'Eritrea' },
  { code: 233, iso3: 'EST', name: 'Estonia' },
  { code: 234, iso3: 'FRO', name: 'Faroe Isds' },
  { code: 242, iso3: 'FJI', name: 'Fiji' },
  { code: 246, iso3: 'FIN', name: 'Finland' },
  { code: 251, iso3: 'FRA', name: 'France' },
  { code: 254, iso3: 'GUF', name: 'French Guiana (Overseas France)' },
  { code: 258, iso3: 'PYF', name: 'French Polynesia' },
  { code: 262, iso3: 'DJI', name: 'Djibouti' },
  { code: 266, iso3: 'GAB', name: 'Gabon' },
  { code: 268, iso3: 'GEO', name: 'Georgia' },
  { code: 270, iso3: 'GMB', name: 'Gambia' },
  { code: 275, iso3: 'PSE', name: 'State of Palestine' },
  { code: 276, iso3: 'DEU', name: 'Germany' },
  { code: 278, iso3: 'DDR', name: 'Dem. Rep. of Germany (...1990)' },
  { code: 280, iso3: 'DEU', name: 'Fed. Rep. of Germany (...1990)' },
  { code: 288, iso3: 'GHA', name: 'Ghana' },
  { code: 292, iso3: 'GIB', name: 'Gibraltar' },
  { code: 296, iso3: 'KIR', name: 'Kiribati' },
  { code: 300, iso3: 'GRC', name: 'Greece' },
  { code: 304, iso3: 'GRL', name: 'Greenland' },
  { code: 308, iso3: 'GRD', name: 'Grenada' },
  { code: 312, iso3: 'GLP', name: 'Guadeloupe (Overseas France)' },
  { code: 320, iso3: 'GTM', name: 'Guatemala' },
  { code: 324, iso3: 'GIN', name: 'Guinea' },
  { code: 328, iso3: 'GUY', name: 'Guyana' },
  { code: 332, iso3: 'HTI', name: 'Haiti' },
  { code: 336, iso3: 'VAT', name: 'Holy See (Vatican City State)' },
  { code: 340, iso3: 'HND', name: 'Honduras' },
  { code: 344, iso3: 'HKG', name: 'China, Hong Kong SAR' },
  { code: 348, iso3: 'HUN', name: 'Hungary' },
  { code: 352, iso3: 'ISL', name: 'Iceland' },
  { code: 356, iso3: 'IND', name: 'India (...1974)' },
  { code: 360, iso3: 'IDN', name: 'Indonesia' },
  { code: 364, iso3: 'IRN', name: 'Iran' },
  { code: 368, iso3: 'IRQ', name: 'Iraq' },
  { code: 372, iso3: 'IRL', name: 'Ireland' },
  { code: 376, iso3: 'ISR', name: 'Israel' },
  { code: 380, iso3: 'ITA', name: 'Italy' },
  { code: 384, iso3: 'CIV', name: "Côte d'Ivoire" },
  { code: 388, iso3: 'JAM', name: 'Jamaica' },
  { code: 392, iso3: 'JPN', name: 'Japan' },
  { code: 398, iso3: 'KAZ', name: 'Kazakhstan' },
  { code: 400, iso3: 'JOR', name: 'Jordan' },
  { code: 404, iso3: 'KEN', name: 'Kenya' },
  { code: 408, iso3: 'PRK', name: "Dem. People's Rep. of Korea" },
  { code: 410, iso3: 'KOR', name: 'Rep. of Korea' },
  { code: 414, iso3: 'KWT', name: 'Kuwait' },
  { code: 417, iso3: 'KGZ', name: 'Kyrgyzstan' },
  { code: 418, iso3: 'LAO', name: "Lao People's Dem. Rep." },
  { code: 422, iso3: 'LBN', name: 'Lebanon' },
  { code: 426, iso3: 'LSO', name: 'Lesotho' },
  { code: 428, iso3: 'LVA', name: 'Latvia' },
  { code: 430, iso3: 'LBR', name: 'Liberia' },
  { code: 434, iso3: 'LBY', name: 'Libya' },
  { code: 440, iso3: 'LTU', name: 'Lithuania' },
  { code: 442, iso3: 'LUX', name: 'Luxembourg' },
  { code: 446, iso3: 'MAC', name: 'China, Macao SAR' },
  { code: 450, iso3: 'MDG', name: 'Madagascar' },
  { code: 454, iso3: 'MWI', name: 'Malawi' },
  { code: 458, iso3: 'MYS', name: 'Malaysia' },
  { code: 459, iso3: '_PM', name: 'Peninsula Malaysia (...1963)' },
  { code: 461, iso3: '_SH', name: 'Sabah (...1963)' },
  { code: 462, iso3: 'MDV', name: 'Maldives' },
  { code: 466, iso3: 'MLI', name: 'Mali' },
  { code: 470, iso3: 'MLT', name: 'Malta' },
  { code: 474, iso3: 'MTQ', name: 'Martinique (Overseas France)' },
  { code: 478, iso3: 'MRT', name: 'Mauritania' },
  { code: 480, iso3: 'MUS', name: 'Mauritius' },
  { code: 484, iso3: 'MEX', name: 'Mexico' },
  { code: 496, iso3: 'MNG', name: 'Mongolia' },
  { code: 498, iso3: 'MDA', name: 'Rep. of Moldova' },
  { code: 499, iso3: 'MNE', name: 'Montenegro' },
  { code: 500, iso3: 'MSR', name: 'Montserrat' },
  { code: 504, iso3: 'MAR', name: 'Morocco' },
  { code: 508, iso3: 'MOZ', name: 'Mozambique' },
  { code: 512, iso3: 'OMN', name: 'Oman' },
  { code: 516, iso3: 'NAM', name: 'Namibia' },
  { code: 520, iso3: 'NRU', name: 'Naoero' },
  { code: 524, iso3: 'NPL', name: 'Nepal' },
  { code: 528, iso3: 'NLD', name: 'Netherlands' },
  { code: 530, iso3: 'ANT', name: 'Netherlands Antilles (...2010)' },
  { code: 531, iso3: 'CUW', name: 'Curaçao' },
  { code: 532, iso3: 'ANT', name: 'Netherlands Antilles and Aruba (...1985)' },
  { code: 533, iso3: 'ABW', name: 'Aruba' },
  { code: 534, iso3: 'SXM', name: 'Saint Maarten' },
  { code: 535, iso3: 'BES', name: 'Bonaire' },
  { code: 540, iso3: 'NCL', name: 'New Caledonia' },
  { code: 548, iso3: 'VUT', name: 'Vanuatu' },
  { code: 554, iso3: 'NZL', name: 'New Zealand' },
  { code: 558, iso3: 'NIC', name: 'Nicaragua' },
  { code: 562, iso3: 'NER', name: 'Niger' },
  { code: 566, iso3: 'NGA', name: 'Nigeria' },
  { code: 570, iso3: 'NIU', name: 'Niue' },
  { code: 579, iso3: 'NOR', name: 'Norway' },
  { code: 580, iso3: 'MNP', name: 'N. Mariana Isds' },
  { code: 582, iso3: 'PCI', name: 'Pacific Isds (...1991)' },
  { code: 583, iso3: 'FSM', name: 'FS Micronesia' },
  { code: 584, iso3: 'MHL', name: 'Marshall Isds' },
  { code: 585, iso3: 'PLW', name: 'Palau' },
  { code: 586, iso3: 'PAK', name: 'Pakistan' },
  { code: 588, iso3: 'PAK', name: 'East and West Pakistan (...1971)' },
  { code: 590, iso3: 'PAN', name: 'Panama, excl.Canal Zone (...1977)' },
  { code: 591, iso3: 'PAN', name: 'Panama' },
  { code: 592, iso3: 'PCZ', name: 'Panama-Canal-Zone (...1977)' },
  { code: 598, iso3: 'PNG', name: 'Papua New Guinea' },
  { code: 600, iso3: 'PRY', name: 'Paraguay' },
  { code: 604, iso3: 'PER', name: 'Peru' },
  { code: 608, iso3: 'PHL', name: 'Philippines' },
  { code: 616, iso3: 'POL', name: 'Poland' },
  { code: 620, iso3: 'PRT', name: 'Portugal' },
  { code: 624, iso3: 'GNB', name: 'Guinea-Bissau' },
  { code: 626, iso3: 'TLS', name: 'Timor-Leste' },
  { code: 634, iso3: 'QAT', name: 'Qatar' },
  { code: 638, iso3: 'REU', name: 'Réunion (Overseas France)' },
  { code: 642, iso3: 'ROU', name: 'Romania' },
  { code: 643, iso3: 'RUS', name: 'Russian Federation' },
  { code: 646, iso3: 'RWA', name: 'Rwanda' },
  { code: 652, iso3: 'BLM', name: 'Saint Barthélemy' },
  { code: 654, iso3: 'SHN', name: 'Saint Helena' },
  { code: 658, iso3: 'KNA', name: 'Saint Kitts, Nevis and Anguilla (...1980)' },
  { code: 659, iso3: 'KNA', name: 'Saint Kitts and Nevis' },
  { code: 660, iso3: 'AIA', name: 'Anguilla' },
  { code: 662, iso3: 'LCA', name: 'Saint Lucia' },
  { code: 666, iso3: 'SPM', name: 'Saint Pierre and Miquelon' },
  { code: 670, iso3: 'VCT', name: 'Saint Vincent and the Grenadines' },
  { code: 674, iso3: 'SMR', name: 'San Marino' },
  { code: 678, iso3: 'STP', name: 'Sao Tome and Principe' },
  { code: 682, iso3: 'SAU', name: 'Saudi Arabia' },
  { code: 686, iso3: 'SEN', name: 'Senegal' },
  { code: 688, iso3: 'SRB', name: 'Serbia' },
  { code: 690, iso3: 'SYC', name: 'Seychelles' },
  { code: 694, iso3: 'SLE', name: 'Sierra Leone' },
  { code: 699, iso3: 'IND', name: 'India' },
  { code: 702, iso3: 'SGP', name: 'Singapore' },
  { code: 703, iso3: 'SVK', name: 'Slovakia' },
  { code: 704, iso3: 'VNM', name: 'Viet Nam' },
  { code: 705, iso3: 'SVN', name: 'Slovenia' },
  { code: 706, iso3: 'SOM', name: 'Somalia' },
  { code: 710, iso3: 'ZAF', name: 'South Africa' },
  { code: 711, iso3: 'ZA1', name: 'Southern African Customs Union (...1999)' },
  { code: 716, iso3: 'ZWE', name: 'Zimbabwe' },
  { code: 717, iso3: '_RN', name: 'Rhodesia Nyas (...1964)' },
  { code: 720, iso3: 'YMD', name: 'Dem. Yemen (...1990)' },
  { code: 724, iso3: 'ESP', name: 'Spain' },
  { code: 728, iso3: 'SSD', name: 'South Sudan' },
  { code: 729, iso3: 'SDN', name: 'Sudan' },
  { code: 736, iso3: 'SDN', name: 'Sudan (...2011)' },
  { code: 740, iso3: 'SUR', name: 'Suriname' },
  { code: 748, iso3: 'SWZ', name: 'Eswatini' },
  { code: 752, iso3: 'SWE', name: 'Sweden' },
  { code: 757, iso3: 'CHE', name: 'Switzerland' },
  { code: 760, iso3: 'SYR', name: 'Syria' },
  { code: 762, iso3: 'TJK', name: 'Tajikistan' },
  { code: 764, iso3: 'THA', name: 'Thailand' },
  { code: 768, iso3: 'TGO', name: 'Togo' },
  { code: 772, iso3: 'TKL', name: 'Tokelau' },
  { code: 776, iso3: 'TON', name: 'Tonga' },
  { code: 780, iso3: 'TTO', name: 'Trinidad and Tobago' },
  { code: 784, iso3: 'ARE', name: 'United Arab Emirates' },
  { code: 788, iso3: 'TUN', name: 'Tunisia' },
  { code: 792, iso3: 'TUR', name: 'Türkiye' },
  { code: 795, iso3: 'TKM', name: 'Turkmenistan' },
  { code: 796, iso3: 'TCA', name: 'Turks and Caicos Isds' },
  { code: 798, iso3: 'TUV', name: 'Tuvalu' },
  { code: 800, iso3: 'UGA', name: 'Uganda' },
  { code: 804, iso3: 'UKR', name: 'Ukraine' },
  { code: 807, iso3: 'MKD', name: 'North Macedonia' },
  { code: 810, iso3: 'SUN', name: 'USSR (...1990)' },
  { code: 818, iso3: 'EGY', name: 'Egypt' },
  { code: 826, iso3: 'GBR', name: 'United Kingdom' },
  { code: 834, iso3: 'TZA', name: 'United Rep. of Tanzania' },
  { code: 835, iso3: '_TK', name: 'Tanganyika (...1964)' },
  { code: 836, iso3: '_ZP', name: 'Zanzibar and Pemba Isd (...1964)' },
  { code: 841, iso3: 'USA', name: 'USA and Puerto Rico (...1980)' },
  { code: 842, iso3: 'USA', name: 'USA' },
  { code: 850, iso3: 'VIR', name: 'US Virgin Isds (...1980)' },
  { code: 854, iso3: 'BFA', name: 'Burkina Faso' },
  { code: 858, iso3: 'URY', name: 'Uruguay' },
  { code: 860, iso3: 'UZB', name: 'Uzbekistan' },
  { code: 862, iso3: 'VEN', name: 'Venezuela' },
  { code: 866, iso3: 'VDR', name: 'Dem. Rep. of Vietnam (...1974)' },
  { code: 868, iso3: 'VNM', name: 'Rep. of Vietnam (...1974)' },
  { code: 876, iso3: 'WLF', name: 'Wallis and Futuna Isds' },
  { code: 882, iso3: 'WSM', name: 'Samoa' },
  { code: 886, iso3: 'YEM', name: 'Arab Rep. of Yemen (...1990)' },
  { code: 887, iso3: 'YEM', name: 'Yemen' },
  { code: 890, iso3: 'YUG', name: 'Yugoslavia (...1991)' },
  { code: 891, iso3: 'SCG', name: 'Serbia and Montenegro (...2005)' },
  { code: 894, iso3: 'ZMB', name: 'Zambia' },
]);

/** Areas that may appear as a trade partner, including non-reporting areas. */
export const PARTNERS = Object.freeze([
  { code: 0, iso3: 'W00', name: 'World', isGroup: true },
  { code: 4, iso3: 'AFG', name: 'Afghanistan', isGroup: false },
  { code: 8, iso3: 'ALB', name: 'Albania', isGroup: false },
  { code: 10, iso3: 'ATA', name: 'Antarctica', isGroup: false },
  { code: 12, iso3: 'DZA', name: 'Algeria', isGroup: false },
  { code: 16, iso3: 'ASM', name: 'American Samoa', isGroup: false },
  { code: 20, iso3: 'AND', name: 'Andorra', isGroup: false },
  { code: 24, iso3: 'AGO', name: 'Angola', isGroup: false },
  { code: 28, iso3: 'ATG', name: 'Antigua and Barbuda', isGroup: false },
  { code: 31, iso3: 'AZE', name: 'Azerbaijan', isGroup: false },
  { code: 32, iso3: 'ARG', name: 'Argentina', isGroup: false },
  { code: 36, iso3: 'AUS', name: 'Australia', isGroup: false },
  { code: 40, iso3: 'AUT', name: 'Austria', isGroup: false },
  { code: 44, iso3: 'BHS', name: 'Bahamas', isGroup: false },
  { code: 48, iso3: 'BHR', name: 'Bahrain', isGroup: false },
  { code: 50, iso3: 'BGD', name: 'Bangladesh', isGroup: false },
  { code: 51, iso3: 'ARM', name: 'Armenia', isGroup: false },
  { code: 52, iso3: 'BRB', name: 'Barbados', isGroup: false },
  { code: 56, iso3: 'BEL', name: 'Belgium', isGroup: false },
  {
    code: 58,
    iso3: 'BEL',
    name: 'Belgium-Luxembourg (...1998)',
    isGroup: false,
  },
  { code: 60, iso3: 'BMU', name: 'Bermuda', isGroup: false },
  { code: 64, iso3: 'BTN', name: 'Bhutan', isGroup: false },
  {
    code: 68,
    iso3: 'BOL',
    name: 'Bolivia (Plurinational State of)',
    isGroup: false,
  },
  { code: 70, iso3: 'BIH', name: 'Bosnia Herzegovina', isGroup: false },
  { code: 72, iso3: 'BWA', name: 'Botswana', isGroup: false },
  { code: 74, iso3: 'BVT', name: 'Bouvet Island', isGroup: false },
  { code: 76, iso3: 'BRA', name: 'Brazil', isGroup: false },
  { code: 80, iso3: 'ATB', name: 'Br. Antarctic Terr.', isGroup: false },
  { code: 84, iso3: 'BLZ', name: 'Belize', isGroup: false },
  { code: 86, iso3: 'IOT', name: 'Br. Indian Ocean Terr.', isGroup: false },
  { code: 90, iso3: 'SLB', name: 'Solomon Isds', isGroup: false },
  { code: 92, iso3: 'VGB', name: 'Br. Virgin Isds', isGroup: false },
  { code: 96, iso3: 'BRN', name: 'Brunei Darussalam', isGroup: false },
  { code: 100, iso3: 'BGR', name: 'Bulgaria', isGroup: false },
  { code: 104, iso3: 'MMR', name: 'Myanmar', isGroup: false },
  { code: 108, iso3: 'BDI', name: 'Burundi', isGroup: false },
  { code: 112, iso3: 'BLR', name: 'Belarus', isGroup: false },
  { code: 116, iso3: 'KHM', name: 'Cambodia', isGroup: false },
  { code: 120, iso3: 'CMR', name: 'Cameroon', isGroup: false },
  { code: 124, iso3: 'CAN', name: 'Canada', isGroup: false },
  { code: 129, iso3: 'A49', name: 'Caribbean, nes', isGroup: false },
  { code: 132, iso3: 'CPV', name: 'Cabo Verde', isGroup: false },
  { code: 136, iso3: 'CYM', name: 'Cayman Isds', isGroup: false },
  { code: 140, iso3: 'CAF', name: 'Central African Rep.', isGroup: false },
  { code: 144, iso3: 'LKA', name: 'Sri Lanka', isGroup: false },
  { code: 148, iso3: 'TCD', name: 'Chad', isGroup: false },
  { code: 152, iso3: 'CHL', name: 'Chile', isGroup: false },
  { code: 156, iso3: 'CHN', name: 'China', isGroup: false },
  { code: 158, iso3: 'TWN', name: 'Taiwan, Province of China', isGroup: false },
  { code: 162, iso3: 'CXR', name: 'Christmas Isds', isGroup: false },
  { code: 166, iso3: 'CCK', name: 'Cocos Isds', isGroup: false },
  { code: 170, iso3: 'COL', name: 'Colombia', isGroup: false },
  { code: 174, iso3: 'COM', name: 'Comoros', isGroup: false },
  { code: 175, iso3: 'MYT', name: 'Mayotte (Overseas France)', isGroup: false },
  { code: 178, iso3: 'COG', name: 'Congo', isGroup: false },
  { code: 180, iso3: 'COD', name: 'Dem. Rep. of the Congo', isGroup: false },
  { code: 184, iso3: 'COK', name: 'Cook Isds', isGroup: false },
  { code: 188, iso3: 'CRI', name: 'Costa Rica', isGroup: false },
  { code: 191, iso3: 'HRV', name: 'Croatia', isGroup: false },
  { code: 192, iso3: 'CUB', name: 'Cuba', isGroup: false },
  { code: 196, iso3: 'CYP', name: 'Cyprus', isGroup: false },
  { code: 200, iso3: 'CSK', name: 'Czechoslovakia (...1992)', isGroup: false },
  { code: 203, iso3: 'CZE', name: 'Czechia', isGroup: false },
  { code: 204, iso3: 'BEN', name: 'Benin', isGroup: false },
  { code: 208, iso3: 'DNK', name: 'Denmark', isGroup: false },
  { code: 212, iso3: 'DMA', name: 'Dominica', isGroup: false },
  { code: 214, iso3: 'DOM', name: 'Dominican Rep.', isGroup: false },
  { code: 218, iso3: 'ECU', name: 'Ecuador', isGroup: false },
  { code: 221, iso3: 'E29', name: 'Eastern Europe, nes', isGroup: false },
  { code: 222, iso3: 'SLV', name: 'El Salvador', isGroup: false },
  { code: 226, iso3: 'GNQ', name: 'Equatorial Guinea', isGroup: false },
  { code: 230, iso3: 'ETH', name: 'Ethiopia (...1992)', isGroup: false },
  { code: 231, iso3: 'ETH', name: 'Ethiopia', isGroup: false },
  { code: 232, iso3: 'ERI', name: 'Eritrea', isGroup: false },
  { code: 233, iso3: 'EST', name: 'Estonia', isGroup: false },
  { code: 234, iso3: 'FRO', name: 'Faroe Isds', isGroup: false },
  { code: 238, iso3: 'FLK', name: 'Falkland Isds (Malvinas)', isGroup: false },
  {
    code: 239,
    iso3: 'SGS',
    name: 'South Georgia and the South Sandwich Islands',
    isGroup: false,
  },
  { code: 242, iso3: 'FJI', name: 'Fiji', isGroup: false },
  { code: 246, iso3: 'FIN', name: 'Finland', isGroup: false },
  { code: 248, iso3: 'ALA', name: 'Åland Islands ', isGroup: false },
  { code: 250, iso3: 'FRA', name: 'Metropolitan France', isGroup: false },
  { code: 251, iso3: 'FRA', name: 'France', isGroup: false },
  {
    code: 254,
    iso3: 'GUF',
    name: 'French Guiana (Overseas France)',
    isGroup: false,
  },
  { code: 258, iso3: 'PYF', name: 'French Polynesia', isGroup: false },
  { code: 260, iso3: 'ATF', name: 'Fr. South Antarctic Terr.', isGroup: false },
  { code: 262, iso3: 'DJI', name: 'Djibouti', isGroup: false },
  { code: 266, iso3: 'GAB', name: 'Gabon', isGroup: false },
  { code: 268, iso3: 'GEO', name: 'Georgia', isGroup: false },
  { code: 270, iso3: 'GMB', name: 'Gambia', isGroup: false },
  { code: 275, iso3: 'PSE', name: 'State of Palestine', isGroup: false },
  { code: 276, iso3: 'DEU', name: 'Germany', isGroup: false },
  {
    code: 278,
    iso3: 'DDR',
    name: 'Dem. Rep. of Germany (...1990)',
    isGroup: false,
  },
  {
    code: 280,
    iso3: 'DEU',
    name: 'Fed. Rep. of Germany (...1990)',
    isGroup: false,
  },
  { code: 288, iso3: 'GHA', name: 'Ghana', isGroup: false },
  { code: 290, iso3: 'F49', name: 'Northern Africa, nes', isGroup: false },
  { code: 292, iso3: 'GIB', name: 'Gibraltar', isGroup: false },
  { code: 296, iso3: 'KIR', name: 'Kiribati', isGroup: false },
  { code: 300, iso3: 'GRC', name: 'Greece', isGroup: false },
  { code: 304, iso3: 'GRL', name: 'Greenland', isGroup: false },
  { code: 308, iso3: 'GRD', name: 'Grenada', isGroup: false },
  {
    code: 312,
    iso3: 'GLP',
    name: 'Guadeloupe (Overseas France)',
    isGroup: false,
  },
  { code: 316, iso3: 'GUM', name: 'Guam', isGroup: false },
  { code: 320, iso3: 'GTM', name: 'Guatemala', isGroup: false },
  { code: 324, iso3: 'GIN', name: 'Guinea', isGroup: false },
  { code: 328, iso3: 'GUY', name: 'Guyana', isGroup: false },
  { code: 332, iso3: 'HTI', name: 'Haiti', isGroup: false },
  {
    code: 334,
    iso3: 'HMD',
    name: 'Heard Island and McDonald Islands',
    isGroup: false,
  },
  {
    code: 336,
    iso3: 'VAT',
    name: 'Holy See (Vatican City State)',
    isGroup: false,
  },
  { code: 340, iso3: 'HND', name: 'Honduras', isGroup: false },
  { code: 344, iso3: 'HKG', name: 'China, Hong Kong SAR', isGroup: false },
  { code: 348, iso3: 'HUN', name: 'Hungary', isGroup: false },
  { code: 352, iso3: 'ISL', name: 'Iceland', isGroup: false },
  { code: 356, iso3: 'IND', name: 'India (...1974)', isGroup: false },
  { code: 360, iso3: 'IDN', name: 'Indonesia', isGroup: false },
  { code: 364, iso3: 'IRN', name: 'Iran', isGroup: false },
  { code: 368, iso3: 'IRQ', name: 'Iraq', isGroup: false },
  { code: 372, iso3: 'IRL', name: 'Ireland', isGroup: false },
  { code: 376, iso3: 'ISR', name: 'Israel', isGroup: false },
  { code: 380, iso3: 'ITA', name: 'Italy', isGroup: false },
  { code: 384, iso3: 'CIV', name: "Côte d'Ivoire", isGroup: false },
  { code: 388, iso3: 'JAM', name: 'Jamaica', isGroup: false },
  { code: 392, iso3: 'JPN', name: 'Japan', isGroup: false },
  { code: 398, iso3: 'KAZ', name: 'Kazakhstan', isGroup: false },
  { code: 400, iso3: 'JOR', name: 'Jordan', isGroup: false },
  { code: 404, iso3: 'KEN', name: 'Kenya', isGroup: false },
  {
    code: 408,
    iso3: 'PRK',
    name: "Dem. People's Rep. of Korea",
    isGroup: false,
  },
  { code: 410, iso3: 'KOR', name: 'Rep. of Korea', isGroup: false },
  { code: 412, iso3: '_KS', name: 'Kosovo', isGroup: false },
  { code: 414, iso3: 'KWT', name: 'Kuwait', isGroup: false },
  { code: 417, iso3: 'KGZ', name: 'Kyrgyzstan', isGroup: false },
  { code: 418, iso3: 'LAO', name: "Lao People's Dem. Rep.", isGroup: false },
  { code: 422, iso3: 'LBN', name: 'Lebanon', isGroup: false },
  { code: 426, iso3: 'LSO', name: 'Lesotho', isGroup: false },
  { code: 428, iso3: 'LVA', name: 'Latvia', isGroup: false },
  { code: 430, iso3: 'LBR', name: 'Liberia', isGroup: false },
  { code: 434, iso3: 'LBY', name: 'Libya', isGroup: false },
  { code: 438, iso3: 'LIE', name: 'Liechtenstein ', isGroup: false },
  { code: 440, iso3: 'LTU', name: 'Lithuania', isGroup: false },
  { code: 442, iso3: 'LUX', name: 'Luxembourg', isGroup: false },
  { code: 446, iso3: 'MAC', name: 'China, Macao SAR', isGroup: false },
  { code: 450, iso3: 'MDG', name: 'Madagascar', isGroup: false },
  { code: 454, iso3: 'MWI', name: 'Malawi', isGroup: false },
  { code: 457, iso3: '_SK', name: 'Sarawak', isGroup: false },
  { code: 458, iso3: 'MYS', name: 'Malaysia', isGroup: false },
  {
    code: 459,
    iso3: '_PM',
    name: 'Peninsula Malaysia (...1963)',
    isGroup: false,
  },
  { code: 461, iso3: '_SH', name: 'Sabah (...1963)', isGroup: false },
  { code: 462, iso3: 'MDV', name: 'Maldives', isGroup: false },
  { code: 466, iso3: 'MLI', name: 'Mali', isGroup: false },
  { code: 470, iso3: 'MLT', name: 'Malta', isGroup: false },
  { code: 471, iso3: 'R91', name: 'CACM, nes', isGroup: false },
  { code: 472, iso3: '_AC', name: 'Africa CAMEU region, nes', isGroup: false },
  { code: 473, iso3: 'A79', name: 'LAIA, nes', isGroup: false },
  {
    code: 474,
    iso3: 'MTQ',
    name: 'Martinique (Overseas France)',
    isGroup: false,
  },
  { code: 478, iso3: 'MRT', name: 'Mauritania', isGroup: false },
  { code: 480, iso3: 'MUS', name: 'Mauritius', isGroup: false },
  { code: 484, iso3: 'MEX', name: 'Mexico', isGroup: false },
  { code: 488, iso3: '_MI', name: 'Midway Islands', isGroup: false },
  { code: 490, iso3: 'S19', name: 'Other Asia, nes', isGroup: false },
  { code: 492, iso3: 'MCO', name: 'Europe EU, nes', isGroup: false },
  { code: 496, iso3: 'MNG', name: 'Mongolia', isGroup: false },
  { code: 498, iso3: 'MDA', name: 'Rep. of Moldova', isGroup: false },
  { code: 499, iso3: 'MNE', name: 'Montenegro', isGroup: false },
  { code: 500, iso3: 'MSR', name: 'Montserrat', isGroup: false },
  { code: 504, iso3: 'MAR', name: 'Morocco', isGroup: false },
  { code: 508, iso3: 'MOZ', name: 'Mozambique', isGroup: false },
  { code: 512, iso3: 'OMN', name: 'Oman', isGroup: false },
  { code: 516, iso3: 'NAM', name: 'Namibia', isGroup: false },
  { code: 520, iso3: 'NRU', name: 'Naoero', isGroup: false },
  { code: 524, iso3: 'NPL', name: 'Nepal', isGroup: false },
  { code: 527, iso3: 'O19', name: 'Oceania, nes', isGroup: false },
  { code: 528, iso3: 'NLD', name: 'Netherlands', isGroup: false },
  {
    code: 530,
    iso3: 'ANT',
    name: 'Netherlands Antilles (...2010)',
    isGroup: false,
  },
  { code: 531, iso3: 'CUW', name: 'Curaçao', isGroup: false },
  {
    code: 532,
    iso3: 'ANT',
    name: 'Netherlands Antilles and Aruba (...1985)',
    isGroup: false,
  },
  { code: 533, iso3: 'ABW', name: 'Aruba', isGroup: false },
  { code: 534, iso3: 'SXM', name: 'Saint Maarten', isGroup: false },
  { code: 535, iso3: 'BES', name: 'Bonaire', isGroup: false },
  { code: 536, iso3: 'NTZ', name: 'Neutral Zone', isGroup: false },
  { code: 540, iso3: 'NCL', name: 'New Caledonia', isGroup: false },
  { code: 548, iso3: 'VUT', name: 'Vanuatu', isGroup: false },
  { code: 554, iso3: 'NZL', name: 'New Zealand', isGroup: false },
  { code: 558, iso3: 'NIC', name: 'Nicaragua', isGroup: false },
  { code: 562, iso3: 'NER', name: 'Niger', isGroup: false },
  { code: 566, iso3: 'NGA', name: 'Nigeria', isGroup: false },
  { code: 568, iso3: 'E19', name: 'Other Europe, nes', isGroup: false },
  { code: 570, iso3: 'NIU', name: 'Niue', isGroup: false },
  { code: 574, iso3: 'NFK', name: 'Norfolk Isds', isGroup: false },
  { code: 577, iso3: 'F19', name: 'Other Africa, nes', isGroup: false },
  {
    code: 578,
    iso3: 'NOR',
    name: 'Norway, excluding Svalbard and Jan Mayen',
    isGroup: false,
  },
  { code: 579, iso3: 'NOR', name: 'Norway', isGroup: false },
  { code: 580, iso3: 'MNP', name: 'N. Mariana Isds', isGroup: false },
  {
    code: 581,
    iso3: 'UMI',
    name: 'United States Minor Outlying Islands',
    isGroup: false,
  },
  { code: 582, iso3: 'PCI', name: 'Pacific Isds (...1991)', isGroup: false },
  { code: 583, iso3: 'FSM', name: 'FS Micronesia', isGroup: false },
  { code: 584, iso3: 'MHL', name: 'Marshall Isds', isGroup: false },
  { code: 585, iso3: 'PLW', name: 'Palau', isGroup: false },
  { code: 586, iso3: 'PAK', name: 'Pakistan', isGroup: false },
  {
    code: 588,
    iso3: 'PAK',
    name: 'East and West Pakistan (...1971)',
    isGroup: false,
  },
  {
    code: 590,
    iso3: 'PAN',
    name: 'Panama, excl.Canal Zone (...1977)',
    isGroup: false,
  },
  { code: 591, iso3: 'PAN', name: 'Panama', isGroup: false },
  {
    code: 592,
    iso3: 'PCZ',
    name: 'Panama-Canal-Zone (...1977)',
    isGroup: false,
  },
  { code: 598, iso3: 'PNG', name: 'Papua New Guinea', isGroup: false },
  { code: 600, iso3: 'PRY', name: 'Paraguay', isGroup: false },
  { code: 604, iso3: 'PER', name: 'Peru', isGroup: false },
  { code: 608, iso3: 'PHL', name: 'Philippines', isGroup: false },
  { code: 612, iso3: 'PCN', name: 'Pitcairn', isGroup: false },
  { code: 616, iso3: 'POL', name: 'Poland', isGroup: false },
  { code: 620, iso3: 'PRT', name: 'Portugal', isGroup: false },
  { code: 624, iso3: 'GNB', name: 'Guinea-Bissau', isGroup: false },
  { code: 626, iso3: 'TLS', name: 'Timor-Leste', isGroup: false },
  { code: 630, iso3: 'PRI', name: 'Puerto Rico ', isGroup: false },
  { code: 634, iso3: 'QAT', name: 'Qatar', isGroup: false },
  { code: 636, iso3: 'A79', name: 'Rest of America, nes', isGroup: false },
  {
    code: 637,
    iso3: 'A59',
    name: 'North America and Central America, nes',
    isGroup: false,
  },
  { code: 638, iso3: 'REU', name: 'Réunion (Overseas France)', isGroup: false },
  { code: 642, iso3: 'ROU', name: 'Romania', isGroup: false },
  { code: 643, iso3: 'RUS', name: 'Russian Federation', isGroup: false },
  { code: 646, iso3: 'RWA', name: 'Rwanda', isGroup: false },
  { code: 647, iso3: '_RI', name: 'Ryukyu Isd', isGroup: false },
  { code: 652, iso3: 'BLM', name: 'Saint Barthélemy', isGroup: false },
  { code: 654, iso3: 'SHN', name: 'Saint Helena', isGroup: false },
  {
    code: 658,
    iso3: 'KNA',
    name: 'Saint Kitts, Nevis and Anguilla (...1980)',
    isGroup: false,
  },
  { code: 659, iso3: 'KNA', name: 'Saint Kitts and Nevis', isGroup: false },
  { code: 660, iso3: 'AIA', name: 'Anguilla', isGroup: false },
  { code: 662, iso3: 'LCA', name: 'Saint Lucia', isGroup: false },
  {
    code: 663,
    iso3: 'MAF',
    name: 'Saint Martin (French part) ',
    isGroup: false,
  },
  { code: 666, iso3: 'SPM', name: 'Saint Pierre and Miquelon', isGroup: false },
  {
    code: 670,
    iso3: 'VCT',
    name: 'Saint Vincent and the Grenadines',
    isGroup: false,
  },
  { code: 674, iso3: 'SMR', name: 'San Marino', isGroup: false },
  { code: 678, iso3: 'STP', name: 'Sao Tome and Principe', isGroup: false },
  { code: 682, iso3: 'SAU', name: 'Saudi Arabia', isGroup: false },
  { code: 686, iso3: 'SEN', name: 'Senegal', isGroup: false },
  { code: 688, iso3: 'SRB', name: 'Serbia', isGroup: false },
  { code: 690, iso3: 'SYC', name: 'Seychelles', isGroup: false },
  { code: 694, iso3: 'SLE', name: 'Sierra Leone', isGroup: false },
  { code: 697, iso3: 'R20', name: 'Europe EFTA, nes', isGroup: false },
  {
    code: 698,
    iso3: '_SM',
    name: 'Sikkim, Protectorate of India (...1974)',
    isGroup: false,
  },
  { code: 699, iso3: 'IND', name: 'India', isGroup: false },
  { code: 702, iso3: 'SGP', name: 'Singapore', isGroup: false },
  { code: 703, iso3: 'SVK', name: 'Slovakia', isGroup: false },
  { code: 704, iso3: 'VNM', name: 'Viet Nam', isGroup: false },
  { code: 705, iso3: 'SVN', name: 'Slovenia', isGroup: false },
  { code: 706, iso3: 'SOM', name: 'Somalia', isGroup: false },
  { code: 710, iso3: 'ZAF', name: 'South Africa', isGroup: false },
  {
    code: 711,
    iso3: 'ZA1',
    name: 'Southern African Customs Union (...1999)',
    isGroup: false,
  },
  { code: 716, iso3: 'ZWE', name: 'Zimbabwe', isGroup: false },
  { code: 717, iso3: '_RN', name: 'Rhodesia Nyas (...1964)', isGroup: false },
  { code: 720, iso3: 'YMD', name: 'Dem. Yemen (...1990)', isGroup: false },
  { code: 724, iso3: 'ESP', name: 'Spain', isGroup: false },
  { code: 728, iso3: 'SSD', name: 'South Sudan', isGroup: false },
  { code: 729, iso3: 'SDN', name: 'Sudan', isGroup: false },
  { code: 732, iso3: 'ESH', name: 'Western Sahara', isGroup: false },
  { code: 736, iso3: 'SDN', name: 'Sudan (...2011)', isGroup: false },
  { code: 740, iso3: 'SUR', name: 'Suriname', isGroup: false },
  {
    code: 744,
    iso3: 'SJM',
    name: 'Svalbard and Jan Mayen Islands ',
    isGroup: false,
  },
  { code: 748, iso3: 'SWZ', name: 'Eswatini', isGroup: false },
  { code: 752, iso3: 'SWE', name: 'Sweden', isGroup: false },
  { code: 756, iso3: 'CHE', name: 'Switzerland ', isGroup: false },
  { code: 757, iso3: 'CHE', name: 'Switzerland', isGroup: false },
  { code: 760, iso3: 'SYR', name: 'Syria', isGroup: false },
  { code: 762, iso3: 'TJK', name: 'Tajikistan', isGroup: false },
  { code: 764, iso3: 'THA', name: 'Thailand', isGroup: false },
  { code: 768, iso3: 'TGO', name: 'Togo', isGroup: false },
  { code: 772, iso3: 'TKL', name: 'Tokelau', isGroup: false },
  { code: 776, iso3: 'TON', name: 'Tonga', isGroup: false },
  { code: 780, iso3: 'TTO', name: 'Trinidad and Tobago', isGroup: false },
  { code: 784, iso3: 'ARE', name: 'United Arab Emirates', isGroup: false },
  { code: 788, iso3: 'TUN', name: 'Tunisia', isGroup: false },
  { code: 792, iso3: 'TUR', name: 'Türkiye', isGroup: false },
  { code: 795, iso3: 'TKM', name: 'Turkmenistan', isGroup: false },
  { code: 796, iso3: 'TCA', name: 'Turks and Caicos Isds', isGroup: false },
  { code: 798, iso3: 'TUV', name: 'Tuvalu', isGroup: false },
  { code: 800, iso3: 'UGA', name: 'Uganda', isGroup: false },
  { code: 804, iso3: 'UKR', name: 'Ukraine', isGroup: false },
  { code: 807, iso3: 'MKD', name: 'North Macedonia', isGroup: false },
  { code: 810, iso3: 'SUN', name: 'USSR (...1990)', isGroup: false },
  { code: 818, iso3: 'EGY', name: 'Egypt', isGroup: false },
  { code: 826, iso3: 'GBR', name: 'United Kingdom', isGroup: false },
  { code: 830, iso3: '_CI', name: 'Channel Islands ', isGroup: false },
  { code: 831, iso3: 'GGY', name: 'Guernsey', isGroup: false },
  { code: 832, iso3: 'JEY', name: 'Jersey', isGroup: false },
  { code: 833, iso3: 'IMN', name: 'Isle of Man ', isGroup: false },
  { code: 834, iso3: 'TZA', name: 'United Rep. of Tanzania', isGroup: false },
  { code: 835, iso3: '_TK', name: 'Tanganyika (...1964)', isGroup: false },
  {
    code: 836,
    iso3: '_ZP',
    name: 'Zanzibar and Pemba Isd (...1964)',
    isGroup: false,
  },
  { code: 837, iso3: 'X1 ', name: 'Bunkers', isGroup: false },
  { code: 838, iso3: 'X2 ', name: 'Free Zones', isGroup: false },
  { code: 839, iso3: 'XX ', name: 'Special Categories', isGroup: false },
  { code: 840, iso3: 'USA', name: 'United States of America', isGroup: false },
  {
    code: 841,
    iso3: 'USA',
    name: 'USA and Puerto Rico (...1980)',
    isGroup: false,
  },
  { code: 842, iso3: 'USA', name: 'USA', isGroup: false },
  { code: 849, iso3: 'PUS', name: 'US Misc. Pacific Isds', isGroup: false },
  { code: 850, iso3: 'VIR', name: 'US Virgin Isds (...1980)', isGroup: false },
  { code: 854, iso3: 'BFA', name: 'Burkina Faso', isGroup: false },
  { code: 858, iso3: 'URY', name: 'Uruguay', isGroup: false },
  { code: 860, iso3: 'UZB', name: 'Uzbekistan', isGroup: false },
  { code: 862, iso3: 'VEN', name: 'Venezuela', isGroup: false },
  {
    code: 866,
    iso3: 'VDR',
    name: 'Dem. Rep. of Vietnam (...1974)',
    isGroup: false,
  },
  { code: 868, iso3: 'VNM', name: 'Rep. of Vietnam (...1974)', isGroup: false },
  { code: 872, iso3: '_WI', name: 'Wake Island', isGroup: false },
  { code: 876, iso3: 'WLF', name: 'Wallis and Futuna Isds', isGroup: false },
  { code: 879, iso3: 'F97', name: 'Western Asia, nes', isGroup: false },
  { code: 882, iso3: 'WSM', name: 'Samoa', isGroup: false },
  {
    code: 886,
    iso3: 'YEM',
    name: 'Arab Rep. of Yemen (...1990)',
    isGroup: false,
  },
  { code: 887, iso3: 'YEM', name: 'Yemen', isGroup: false },
  { code: 890, iso3: 'YUG', name: 'Yugoslavia (...1991)', isGroup: false },
  {
    code: 891,
    iso3: 'SCG',
    name: 'Serbia and Montenegro (...2005)',
    isGroup: false,
  },
  { code: 894, iso3: 'ZMB', name: 'Zambia', isGroup: false },
  { code: 899, iso3: '_X ', name: 'Areas, nes', isGroup: false },
]);
