/**
 * Major world ports.
 *
 * Filtered from the NGA World Port Index to harbour sizes L and M. WPI's
 * smaller classes (S and V) are mostly marinas and fishing harbours, which
 * are not trade infrastructure.
 *
 * ONLY the fields measured to be reliably populated are carried through
 * (see docs/DATA_AVAILABILITY_MATRIX.md §1.2). In particular the cargo
 * facility flags — loContainer, loOilTerm, loSolidBulk, loRoro — are ~1%
 * populated and are DELIBERATELY OMITTED. Port commodity specialization
 * cannot be sourced from this dataset, and a 1%-populated field masquerading
 * as a fact is worse than an acknowledged gap.
 *
 * `size` is a 4-level ordinal (L/M/S/V), NOT throughput. `channelDepthFt` is
 * a physical capacity proxy, not a berth count or a TEU figure.
 *
 * `rail` is "Y", "N" or "U". About half of all rows are "U": absence of rail
 * data is not evidence of absent rail.
 *
 * GENERATED FILE. Regenerate with `node scripts/build-geo-reference.mjs`.
 *
 * Source:  NGA World Port Index, retrieved 2026-09-16
 * Licence: US Government public domain (17 U.S.C. 105)
 *
 * Portable: no Cesium, no Node, no browser globals.
 */

/** 417 ports (135 large, 282 medium). */
export const MAJOR_PORTS = Object.freeze([
  {
    id: 'wpi:48430',
    name: 'Abadan',
    country: 'IR',
    lat: 30.3333,
    lon: 48.2833,
    size: 'M',
    harborType: 'RN',
    unlocode: 'IRABD',
    channelDepthFt: 9,
    rail: 'U',
  },
  {
    id: 'wpi:32220',
    name: 'Aberdeen',
    country: 'GB',
    lat: 57.15,
    lon: -2.0833,
    size: 'M',
    harborType: 'RB',
    unlocode: 'GBABD',
    channelDepthFt: 5,
    rail: 'Y',
  },
  {
    id: 'wpi:48278',
    name: 'Abu Zaby',
    country: 'AE',
    lat: 24.5,
    lon: 54.3333,
    size: 'M',
    harborType: 'CB',
    unlocode: 'AEAUH',
    channelDepthFt: 14,
    rail: 'Y',
  },
  {
    id: 'wpi:15760',
    name: 'Acapulco',
    country: 'MX',
    lat: 16.85,
    lon: -99.9333,
    size: 'M',
    harborType: 'CN',
    unlocode: 'MXACA',
    channelDepthFt: 0,
    rail: 'Y',
  },
  {
    id: 'wpi:45802',
    name: 'Agadir',
    country: 'MA',
    lat: 30.4333,
    lon: -9.6333,
    size: 'L',
    harborType: 'CB',
    unlocode: 'MAAGA',
    channelDepthFt: 8,
    rail: 'U',
  },
  {
    id: 'wpi:48400',
    name: 'Al Basrah',
    country: 'IQ',
    lat: 30.5167,
    lon: 47.8333,
    size: 'M',
    harborType: 'RN',
    unlocode: 'IQBSR',
    channelDepthFt: 0,
    rail: 'U',
  },
  {
    id: 'wpi:45165',
    name: 'Al Iskandariyh (Alexandria)',
    country: 'EG',
    lat: 31.1667,
    lon: 29.8333,
    size: 'L',
    harborType: 'CB',
    unlocode: 'EGALY',
    channelDepthFt: 14,
    rail: 'Y',
  },
  {
    id: 'wpi:48175',
    name: 'Al Mukha',
    country: 'YE',
    lat: 13.3167,
    lon: 43.25,
    size: 'M',
    harborType: 'CN',
    unlocode: 'YEMOK',
    channelDepthFt: 8,
    rail: 'U',
  },
  {
    id: 'wpi:7720',
    name: 'Albany',
    country: 'US',
    lat: 42.65,
    lon: -73.75,
    size: 'M',
    harborType: 'RN',
    unlocode: 'USALB',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:42630',
    name: 'Alexandroupoli',
    country: 'GR',
    lat: 40.8333,
    lon: 25.8833,
    size: 'M',
    harborType: 'CB',
    unlocode: 'GRAXD',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:45570',
    name: 'Alger',
    country: 'DZ',
    lat: 36.7667,
    lon: 3.0667,
    size: 'L',
    harborType: 'CB',
    unlocode: 'DZALG',
    channelDepthFt: 19,
    rail: 'Y',
  },
  {
    id: 'wpi:38440',
    name: 'Alicante',
    country: 'ES',
    lat: 38.3333,
    lon: -0.4833,
    size: 'M',
    harborType: 'CB',
    unlocode: 'ESALC',
    channelDepthFt: 14,
    rail: 'Y',
  },
  {
    id: 'wpi:31060',
    name: 'Amsterdam',
    country: 'NL',
    lat: 52.3667,
    lon: 4.9,
    size: 'L',
    harborType: 'LC',
    unlocode: 'NLAMS',
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:45490',
    name: 'Annaba',
    country: 'DZ',
    lat: 36.9167,
    lon: 7.7667,
    size: 'M',
    harborType: 'CB',
    unlocode: 'DZAAE',
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:14660',
    name: 'Antofagasta',
    country: 'CL',
    lat: -23.65,
    lon: -70.4167,
    size: 'M',
    harborType: 'CB',
    unlocode: 'CLANF',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:31250',
    name: 'Antwerpen',
    country: 'BE',
    lat: 51.2167,
    lon: 4.4,
    size: 'L',
    harborType: 'RT',
    unlocode: 'BEANR',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:56550',
    name: 'Apra Harbor',
    country: 'GU',
    lat: 13.45,
    lon: 144.6167,
    size: 'M',
    harborType: 'CB',
    unlocode: 'GUAPR',
    channelDepthFt: 11,
    rail: 'U',
  },
  {
    id: 'wpi:48040',
    name: 'As Suways',
    country: 'EG',
    lat: 29.9667,
    lon: 32.55,
    size: 'L',
    harborType: 'CB',
    unlocode: 'EGSUZ',
    channelDepthFt: 19,
    rail: 'Y',
  },
  {
    id: 'wpi:55060',
    name: 'Auckland',
    country: 'NZ',
    lat: -36.85,
    lon: 174.7667,
    size: 'L',
    harborType: 'RN',
    unlocode: 'NZAKL',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:40250',
    name: 'Augusta',
    country: 'IT',
    lat: 37.2167,
    lon: 15.2333,
    size: 'M',
    harborType: 'CB',
    unlocode: 'ITAUG',
    channelDepthFt: 23,
    rail: 'Y',
  },
  {
    id: 'wpi:37970',
    name: 'Aveiro',
    country: 'PT',
    lat: 40.65,
    lon: -8.65,
    size: 'M',
    harborType: 'RN',
    unlocode: 'PTAVE',
    channelDepthFt: 6,
    rail: 'Y',
  },
  {
    id: 'wpi:14500',
    name: 'Bahia De Valparaiso',
    country: 'CL',
    lat: -33.0333,
    lon: -71.6167,
    size: 'M',
    harborType: 'CB',
    unlocode: 'CLVAP',
    channelDepthFt: 23,
    rail: 'Y',
  },
  {
    id: 'wpi:15410',
    name: 'Balboa',
    country: 'PA',
    lat: 8.95,
    lon: -79.5667,
    size: 'M',
    harborType: 'LC',
    unlocode: 'PABLB',
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:8210',
    name: 'Baltimore',
    country: 'US',
    lat: 39.2667,
    lon: -76.5833,
    size: 'L',
    harborType: 'RN',
    unlocode: 'USBAL',
    channelDepthFt: 14,
    rail: 'Y',
  },
  {
    id: 'wpi:45280',
    name: 'Banghazi',
    country: 'LY',
    lat: 32.1167,
    lon: 20.05,
    size: 'M',
    harborType: 'CB',
    unlocode: 'LYBEN',
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:57450',
    name: 'Bangkok',
    country: 'TH',
    lat: 13.75,
    lon: 100.5,
    size: 'L',
    harborType: 'RN',
    unlocode: 'THBKK',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:38550',
    name: 'Barcelona',
    country: 'ES',
    lat: 41.35,
    lon: 2.1667,
    size: 'L',
    harborType: 'CB',
    unlocode: 'ESBCN',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:40530',
    name: 'Bari',
    country: 'IT',
    lat: 41.146,
    lon: 16.846,
    size: 'M',
    harborType: 'CB',
    unlocode: 'ITBRI',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:34630',
    name: 'Barrow In Furness',
    country: 'GB',
    lat: 54.1167,
    lon: -3.2333,
    size: 'M',
    harborType: 'CT',
    unlocode: 'GBBIF',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:34990',
    name: 'Barry',
    country: 'GB',
    lat: 51.4,
    lon: -3.2667,
    size: 'M',
    harborType: 'CT',
    unlocode: 'GBBAD',
    channelDepthFt: 2,
    rail: 'Y',
  },
  {
    id: 'wpi:58320',
    name: 'Batangas City',
    country: 'PH',
    lat: 13.75,
    lon: 121.05,
    size: 'M',
    harborType: 'OR',
    unlocode: 'PHBTG',
    channelDepthFt: 23,
    rail: 'Y',
  },
  {
    id: 'wpi:37230',
    name: 'Bayonne',
    country: 'FR',
    lat: 43.5,
    lon: -1.4667,
    size: 'M',
    harborType: 'RN',
    unlocode: 'FRBAY',
    channelDepthFt: 5,
    rail: 'Y',
  },
  {
    id: 'wpi:7790',
    name: 'Bayonne',
    country: 'US',
    lat: 40.6833,
    lon: -74.1,
    size: 'M',
    harborType: 'RN',
    unlocode: 'USBAY',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:9140',
    name: 'Beaumont',
    country: 'US',
    lat: 30.0833,
    lon: -94.0833,
    size: 'M',
    harborType: 'RN',
    unlocode: 'USBPT',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:46890',
    name: 'Beira',
    country: 'MZ',
    lat: -19.8333,
    lon: 34.8333,
    size: 'M',
    harborType: 'CN',
    unlocode: 'MZBEW',
    channelDepthFt: 5,
    rail: 'Y',
  },
  {
    id: 'wpi:50730',
    name: 'Belawan',
    country: 'ID',
    lat: 3.7833,
    lon: 98.6833,
    size: 'M',
    harborType: 'RN',
    unlocode: 'IDBLW',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:12490',
    name: 'Belem',
    country: 'BR',
    lat: -1.45,
    lon: -48.5,
    size: 'M',
    harborType: 'RN',
    unlocode: 'BRBEL',
    channelDepthFt: 3,
    rail: 'Y',
  },
  {
    id: 'wpi:33770',
    name: 'Belfast',
    country: 'GB',
    lat: 54.6167,
    lon: -5.9,
    size: 'L',
    harborType: 'RB',
    unlocode: 'GBBEL',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:47944',
    name: 'Beshayer Oil Terminal',
    country: 'SD',
    lat: 19.4,
    lon: 37.3167,
    size: 'M',
    harborType: 'OR',
    unlocode: null,
    channelDepthFt: 0,
    rail: 'U',
  },
  {
    id: 'wpi:31820',
    name: 'Blyth',
    country: 'GB',
    lat: 55.1167,
    lon: -1.5,
    size: 'M',
    harborType: 'RN',
    unlocode: 'GBBLY',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:37190',
    name: 'Bordeaux',
    country: 'FR',
    lat: 44.8667,
    lon: -0.5667,
    size: 'L',
    harborType: 'RT',
    unlocode: 'FRBOD',
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:7250',
    name: 'Boston',
    country: 'US',
    lat: 42.35,
    lon: -71.05,
    size: 'L',
    harborType: 'CN',
    unlocode: 'USBOS',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:35760',
    name: 'Boulogne-Sur-Mer',
    country: 'FR',
    lat: 50.7333,
    lon: 1.6,
    size: 'M',
    harborType: 'RT',
    unlocode: 'FRBOL',
    channelDepthFt: 5,
    rail: 'Y',
  },
  {
    id: 'wpi:30850',
    name: 'Brake',
    country: 'DE',
    lat: 53.3333,
    lon: 8.4833,
    size: 'M',
    harborType: 'RT',
    unlocode: 'DEBKE',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:30900',
    name: 'Bremen',
    country: 'DE',
    lat: 53.1333,
    lon: 8.7667,
    size: 'L',
    harborType: 'RT',
    unlocode: 'DEBRE',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:30810',
    name: 'Bremerhaven',
    country: 'DE',
    lat: 53.5333,
    lon: 8.5833,
    size: 'L',
    harborType: 'RT',
    unlocode: 'DEBRV',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:17430',
    name: 'Bremerton',
    country: 'US',
    lat: 47.5667,
    lon: -122.65,
    size: 'M',
    harborType: 'CN',
    unlocode: 'USPWT',
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:7570',
    name: 'Bridgeport',
    country: 'US',
    lat: 41.1667,
    lon: -73.1833,
    size: 'M',
    harborType: 'CB',
    unlocode: 'USBDR',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:40500',
    name: 'Brindisi',
    country: 'IT',
    lat: 40.65,
    lon: 17.9833,
    size: 'L',
    harborType: 'CB',
    unlocode: 'ITBDS',
    channelDepthFt: 14,
    rail: 'Y',
  },
  {
    id: 'wpi:35070',
    name: 'Bristol',
    country: 'GB',
    lat: 51.4667,
    lon: -2.6333,
    size: 'M',
    harborType: 'RT',
    unlocode: 'GBBRS',
    channelDepthFt: 6,
    rail: 'U',
  },
  {
    id: 'wpi:7630',
    name: 'Brooklyn',
    country: 'US',
    lat: 40.6667,
    lon: -74.0167,
    size: 'L',
    harborType: 'RN',
    unlocode: 'USBOY',
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:13760',
    name: 'Buenos Aires',
    country: 'AR',
    lat: -34.6,
    lon: -58.3667,
    size: 'L',
    harborType: 'CB',
    unlocode: 'ARBUE',
    channelDepthFt: 6,
    rail: 'Y',
  },
  {
    id: 'wpi:3430',
    name: 'Buffalo',
    country: 'US',
    lat: 42.8833,
    lon: -78.8833,
    size: 'L',
    harborType: 'CB',
    unlocode: 'USBUF',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:4770',
    name: 'Buffington',
    country: 'US',
    lat: 41.6333,
    lon: -87.4167,
    size: 'M',
    harborType: 'CB',
    unlocode: null,
    channelDepthFt: 8,
    rail: 'U',
  },
  {
    id: 'wpi:45140',
    name: "Bur Sa'id",
    country: 'EG',
    lat: 31.2667,
    lon: 32.3,
    size: 'L',
    harborType: 'LC',
    unlocode: 'EGPSD',
    channelDepthFt: 14,
    rail: 'Y',
  },
  {
    id: 'wpi:60390',
    name: 'Busan',
    country: 'KR',
    lat: 35.1,
    lon: 129.0333,
    size: 'L',
    harborType: 'CB',
    unlocode: 'KRPUS',
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:48470',
    name: 'Bushehr',
    country: 'IR',
    lat: 28.9833,
    lon: 50.8333,
    size: 'M',
    harborType: 'CN',
    unlocode: 'IRBUZ',
    channelDepthFt: 6,
    rail: 'U',
  },
  {
    id: 'wpi:38290',
    name: 'Cadiz',
    country: 'ES',
    lat: 36.5333,
    lon: -6.3,
    size: 'M',
    harborType: 'CB',
    unlocode: 'ESCAD',
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:59710',
    name: 'Cagayan De Oro',
    country: 'PH',
    lat: 8.5,
    lon: 124.6667,
    size: 'M',
    harborType: 'CN',
    unlocode: 'PHCGY',
    channelDepthFt: 23,
    rail: 'U',
  },
  {
    id: 'wpi:39210',
    name: 'Cagliari',
    country: 'IT',
    lat: 39.19,
    lon: 9.102,
    size: 'M',
    harborType: 'CB',
    unlocode: 'ITCAG',
    channelDepthFt: 14,
    rail: 'Y',
  },
  {
    id: 'wpi:4790',
    name: 'Calumet Harbor',
    country: 'US',
    lat: 41.7333,
    lon: -87.5167,
    size: 'M',
    harborType: 'CB',
    unlocode: 'USCAY',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:8130',
    name: 'Camden',
    country: 'US',
    lat: 39.95,
    lon: -75.1333,
    size: 'M',
    harborType: 'RN',
    unlocode: 'USCDE',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:6545',
    name: 'Canaport (St. John)',
    country: 'CA',
    lat: 45.2,
    lon: -65.9833,
    size: 'L',
    harborType: 'OR',
    unlocode: 'CACPT',
    channelDepthFt: 23,
    rail: 'U',
  },
  {
    id: 'wpi:46770',
    name: 'Cape Town',
    country: 'ZA',
    lat: -33.9167,
    lon: 18.4167,
    size: 'L',
    harborType: 'CB',
    unlocode: 'ZACPT',
    channelDepthFt: 16,
    rail: 'Y',
  },
  {
    id: 'wpi:35010',
    name: 'Cardiff',
    country: 'GB',
    lat: 51.45,
    lon: -3.1667,
    size: 'M',
    harborType: 'CT',
    unlocode: 'GBCDF',
    channelDepthFt: 0,
    rail: 'Y',
  },
  {
    id: 'wpi:45793',
    name: 'Casablanca',
    country: 'MA',
    lat: 33.6,
    lon: -7.6167,
    size: 'L',
    harborType: 'CB',
    unlocode: 'MACAS',
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:40270',
    name: 'Catania',
    country: 'IT',
    lat: 37.5,
    lon: 15.1,
    size: 'M',
    harborType: 'CB',
    unlocode: 'ITCTA',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:58960',
    name: 'Cebu',
    country: 'PH',
    lat: 10.3,
    lon: 123.9,
    size: 'L',
    harborType: 'CB',
    unlocode: 'PHCEB',
    channelDepthFt: 9,
    rail: 'U',
  },
  {
    id: 'wpi:45730',
    name: 'Ceuta',
    country: 'ES',
    lat: 35.9,
    lon: -5.3167,
    size: 'M',
    harborType: 'CB',
    unlocode: 'ESCEU',
    channelDepthFt: 0,
    rail: 'U',
  },
  {
    id: 'wpi:57862',
    name: 'Chaozhou',
    country: 'CN',
    lat: 23.6167,
    lon: 117.0833,
    size: 'M',
    harborType: 'CN',
    unlocode: 'CNCOZ',
    channelDepthFt: 0,
    rail: 'U',
  },
  {
    id: 'wpi:8080',
    name: 'Chester',
    country: 'US',
    lat: 39.85,
    lon: -75.35,
    size: 'L',
    harborType: 'RN',
    unlocode: 'USCHT',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:57890',
    name: 'Chi-Lung',
    country: 'TW',
    lat: 25.1333,
    lon: 121.7667,
    size: 'L',
    harborType: 'CB',
    unlocode: 'TWKEL',
    channelDepthFt: 16,
    rail: 'Y',
  },
  {
    id: 'wpi:4800',
    name: 'Chicago',
    country: 'US',
    lat: 41.8833,
    lon: -87.6,
    size: 'M',
    harborType: 'CT',
    unlocode: 'USCHI',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:51220',
    name: 'Cilacap',
    country: 'ID',
    lat: -7.7333,
    lon: 109,
    size: 'L',
    harborType: 'CN',
    unlocode: 'IDCXP',
    channelDepthFt: 11,
    rail: 'U',
  },
  {
    id: 'wpi:39810',
    name: 'Civitavecchia',
    country: 'IT',
    lat: 42.102,
    lon: 11.771,
    size: 'L',
    harborType: 'CB',
    unlocode: 'ITCVV',
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:3490',
    name: 'Cleveland',
    country: 'US',
    lat: 41.5,
    lon: -81.7167,
    size: 'L',
    harborType: 'CB',
    unlocode: 'USCLE',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:34350',
    name: 'Cobh',
    country: 'IE',
    lat: 51.85,
    lon: -8.3,
    size: 'M',
    harborType: 'RN',
    unlocode: 'IECOB',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:45855',
    name: 'Conakry',
    country: 'GN',
    lat: 9.5167,
    lon: -13.7167,
    size: 'M',
    harborType: 'CB',
    unlocode: 'GNCKY',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:43560',
    name: 'Constanta',
    country: 'RO',
    lat: 44.1667,
    lon: 28.65,
    size: 'M',
    harborType: 'CB',
    unlocode: 'ROCND',
    channelDepthFt: 20,
    rail: 'Y',
  },
  {
    id: 'wpi:34360',
    name: 'Cork',
    country: 'IE',
    lat: 51.85,
    lon: -8.2667,
    size: 'M',
    harborType: 'RN',
    unlocode: 'IEORK',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:9300',
    name: 'Corpus Christi',
    country: 'US',
    lat: 27.8167,
    lon: -97.4,
    size: 'M',
    harborType: 'CN',
    unlocode: 'USCRP',
    channelDepthFt: 14,
    rail: 'Y',
  },
  {
    id: 'wpi:30800',
    name: 'Cuxhaven',
    country: 'DE',
    lat: 53.8667,
    lon: 8.7167,
    size: 'M',
    harborType: 'RB',
    unlocode: 'DECUX',
    channelDepthFt: 14,
    rail: 'Y',
  },
  {
    id: 'wpi:45820',
    name: 'Dakar',
    country: 'SN',
    lat: 14.6833,
    lon: -17.4333,
    size: 'M',
    harborType: 'CB',
    unlocode: 'SNDKR',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:60250',
    name: 'Dalian',
    country: 'CN',
    lat: 38.9167,
    lon: 121.6667,
    size: 'L',
    harborType: 'CB',
    unlocode: 'CNDAL',
    channelDepthFt: 23,
    rail: 'Y',
  },
  {
    id: 'wpi:45151',
    name: 'Damietta',
    country: 'EG',
    lat: 31.4833,
    lon: 31.75,
    size: 'L',
    harborType: 'CB',
    unlocode: 'EGDAM',
    channelDepthFt: 14,
    rail: 'U',
  },
  {
    id: 'wpi:43565',
    name: 'Danube-Black Sea Canal',
    country: 'RO',
    lat: 44.2667,
    lon: 28.1833,
    size: 'M',
    harborType: 'LC',
    unlocode: null,
    channelDepthFt: 6,
    rail: 'U',
  },
  {
    id: 'wpi:47010',
    name: 'Dar Es Salaam',
    country: 'TZ',
    lat: -6.8167,
    lon: 39.3,
    size: 'M',
    harborType: 'CN',
    unlocode: 'TZDAR',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:60810',
    name: 'De Kastri',
    country: 'RU',
    lat: 51.4667,
    lon: 140.7833,
    size: 'M',
    harborType: 'CN',
    unlocode: 'RUDKA',
    channelDepthFt: 7,
    rail: 'U',
  },
  {
    id: 'wpi:3620',
    name: 'Detroit',
    country: 'US',
    lat: 42.3333,
    lon: -83.0333,
    size: 'L',
    harborType: 'RN',
    unlocode: 'USDET',
    channelDepthFt: 6,
    rail: 'Y',
  },
  {
    id: 'wpi:31150',
    name: 'Dordrecht',
    country: 'NL',
    lat: 51.8167,
    lon: 4.65,
    size: 'M',
    harborType: 'RN',
    unlocode: 'NLDOR',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:12900',
    name: 'Dtse / Gegua Oil Terminal',
    country: 'BR',
    lat: -22.8167,
    lon: -43.15,
    size: 'M',
    harborType: 'OR',
    unlocode: null,
    channelDepthFt: 11,
    rail: 'U',
  },
  {
    id: 'wpi:34480',
    name: 'Dublin',
    country: 'IE',
    lat: 53.35,
    lon: -6.25,
    size: 'M',
    harborType: 'CB',
    unlocode: 'IEMTL',
    channelDepthFt: 10,
    rail: 'Y',
  },
  {
    id: 'wpi:62720',
    name: 'Dudinka',
    country: 'RU',
    lat: 69.4,
    lon: 86.1667,
    size: 'M',
    harborType: 'RN',
    unlocode: 'RUDUD',
    channelDepthFt: 6,
    rail: 'Y',
  },
  {
    id: 'wpi:5460',
    name: 'Duluth',
    country: 'US',
    lat: 46.7667,
    lon: -92.1,
    size: 'M',
    harborType: 'CB',
    unlocode: 'USDLH',
    channelDepthFt: 6,
    rail: 'Y',
  },
  {
    id: 'wpi:50785',
    name: 'Dumai',
    country: 'ID',
    lat: 1.6833,
    lon: 101.45,
    size: 'M',
    harborType: 'RN',
    unlocode: 'IDDUM',
    channelDepthFt: 17,
    rail: 'U',
  },
  {
    id: 'wpi:32170',
    name: 'Dundee',
    country: 'GB',
    lat: 56.4667,
    lon: -2.95,
    size: 'L',
    harborType: 'RB',
    unlocode: 'GBDUN',
    channelDepthFt: 6,
    rail: 'Y',
  },
  {
    id: 'wpi:35730',
    name: 'Dunkerque Port Est',
    country: 'FR',
    lat: 51.05,
    lon: 2.3833,
    size: 'M',
    harborType: 'RT',
    unlocode: 'FRDKK',
    channelDepthFt: 14,
    rail: 'Y',
  },
  {
    id: 'wpi:35732',
    name: 'Dunkerque Port Ouest',
    country: 'FR',
    lat: 51.0667,
    lon: 2.35,
    size: 'M',
    harborType: 'CT',
    unlocode: 'FRDKK',
    channelDepthFt: 20,
    rail: 'Y',
  },
  {
    id: 'wpi:46850',
    name: 'Durban',
    country: 'ZA',
    lat: -29.8667,
    lon: 31.0667,
    size: 'L',
    harborType: 'CB',
    unlocode: 'ZADUR',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:30950',
    name: 'Emden',
    country: 'DE',
    lat: 53.3333,
    lon: 7.1833,
    size: 'M',
    harborType: 'RT',
    unlocode: 'DEEME',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:16740',
    name: 'Empire',
    country: 'US',
    lat: 43.4,
    lon: -124.2833,
    size: 'M',
    harborType: 'CN',
    unlocode: null,
    channelDepthFt: 8,
    rail: 'U',
  },
  {
    id: 'wpi:15990',
    name: 'Ensenada',
    country: 'MX',
    lat: 31.8667,
    lon: -116.6333,
    size: 'M',
    harborType: 'CB',
    unlocode: 'MXESE',
    channelDepthFt: 11,
    rail: 'U',
  },
  {
    id: 'wpi:11170',
    name: 'Ensenada Honda',
    country: 'PR',
    lat: 18.2333,
    lon: -65.6333,
    size: 'M',
    harborType: 'CB',
    unlocode: null,
    channelDepthFt: 8,
    rail: 'U',
  },
  {
    id: 'wpi:38330',
    name: 'Europa Point',
    country: 'GI',
    lat: 36.1333,
    lon: -5.35,
    size: 'M',
    harborType: 'CB',
    unlocode: null,
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:31085',
    name: 'Europoort',
    country: 'NL',
    lat: 51.95,
    lon: 4.1167,
    size: 'M',
    harborType: 'LC',
    unlocode: 'NLEUR',
    channelDepthFt: 20,
    rail: 'Y',
  },
  {
    id: 'wpi:35290',
    name: 'Falmouth Harbour',
    country: 'GB',
    lat: 50.15,
    lon: -5.0667,
    size: 'M',
    harborType: 'CN',
    unlocode: 'GBFAL',
    channelDepthFt: 14,
    rail: 'Y',
  },
  {
    id: 'wpi:57745',
    name: 'Fang-Cheng',
    country: 'CN',
    lat: 21.75,
    lon: 108.35,
    size: 'M',
    harborType: 'RN',
    unlocode: 'CNFAN',
    channelDepthFt: 16,
    rail: 'Y',
  },
  {
    id: 'wpi:37740',
    name: 'Ferrol',
    country: 'ES',
    lat: 43.4833,
    lon: -8.2333,
    size: 'M',
    harborType: 'RN',
    unlocode: 'ESFRO',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:50910',
    name: 'Flying Fish Cove',
    country: 'CX',
    lat: -10.4167,
    lon: 105.7,
    size: 'M',
    harborType: 'CN',
    unlocode: 'CXFFC',
    channelDepthFt: 23,
    rail: 'U',
  },
  {
    id: 'wpi:11550',
    name: 'Fort De France',
    country: 'MQ',
    lat: 14.6,
    lon: -61.0667,
    size: 'M',
    harborType: 'OR',
    unlocode: 'MQFDF',
    channelDepthFt: 9,
    rail: 'U',
  },
  {
    id: 'wpi:34130',
    name: 'Foynes',
    country: 'IE',
    lat: 52.6167,
    lon: -9.1167,
    size: 'L',
    harborType: 'RN',
    unlocode: 'IEFOV',
    channelDepthFt: 6,
    rail: 'Y',
  },
  {
    id: 'wpi:54520',
    name: 'Fremantle',
    country: 'AU',
    lat: -32.05,
    lon: 115.75,
    size: 'L',
    harborType: 'CB',
    unlocode: 'AUFRE',
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:61820',
    name: 'Fukui Ko',
    country: 'JP',
    lat: 36.1833,
    lon: 136.1,
    size: 'M',
    harborType: 'RN',
    unlocode: 'JPFKJ',
    channelDepthFt: 8,
    rail: 'U',
  },
  {
    id: 'wpi:61605',
    name: 'Fukuyama',
    country: 'JP',
    lat: 34.4333,
    lon: 133.4333,
    size: 'M',
    harborType: 'CN',
    unlocode: 'JPFYM',
    channelDepthFt: 16,
    rail: 'Y',
  },
  {
    id: 'wpi:38130',
    name: 'Funchal',
    country: 'PT',
    lat: 32.6333,
    lon: -16.9167,
    size: 'L',
    harborType: 'CB',
    unlocode: 'PTFNC',
    channelDepthFt: 13,
    rail: 'U',
  },
  {
    id: 'wpi:40480',
    name: 'Gallipoli',
    country: 'IT',
    lat: 40.06,
    lon: 17.984,
    size: 'M',
    harborType: 'CB',
    unlocode: 'ITGAL',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:9150',
    name: 'Galveston',
    country: 'US',
    lat: 29.3167,
    lon: -94.7833,
    size: 'L',
    harborType: 'CN',
    unlocode: 'USGLS',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:4760',
    name: 'Gary',
    country: 'US',
    lat: 41.6167,
    lon: -87.3333,
    size: 'M',
    harborType: 'CB',
    unlocode: 'USGYY',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:28710',
    name: 'Gdansk',
    country: 'PL',
    lat: 54.35,
    lon: 18.6667,
    size: 'L',
    harborType: 'LC',
    unlocode: 'PLGDN',
    channelDepthFt: 6,
    rail: 'Y',
  },
  {
    id: 'wpi:28740',
    name: 'Gdynia',
    country: 'PL',
    lat: 54.5333,
    lon: 18.55,
    size: 'L',
    harborType: 'CB',
    unlocode: 'PLGDY',
    channelDepthFt: 14,
    rail: 'Y',
  },
  {
    id: 'wpi:39470',
    name: 'Genova',
    country: 'IT',
    lat: 44.398,
    lon: 8.922,
    size: 'L',
    harborType: 'CB',
    unlocode: 'ITGOA',
    channelDepthFt: 16,
    rail: 'Y',
  },
  {
    id: 'wpi:46670',
    name: 'Georgetown',
    country: 'SH',
    lat: -7.9333,
    lon: -14.4167,
    size: 'M',
    harborType: 'OR',
    unlocode: 'SHASI',
    channelDepthFt: 23,
    rail: 'U',
  },
  {
    id: 'wpi:12370',
    name: 'Georgetown',
    country: 'GY',
    lat: 6.8333,
    lon: -58.1667,
    size: 'M',
    harborType: 'RN',
    unlocode: 'GYGEO',
    channelDepthFt: 6,
    rail: 'Y',
  },
  {
    id: 'wpi:31270',
    name: 'Ghent',
    country: 'BE',
    lat: 51.0667,
    lon: 3.7333,
    size: 'M',
    harborType: 'LC',
    unlocode: 'BEGNE',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:40115',
    name: 'Gioia Tauro',
    country: 'IT',
    lat: 38.444,
    lon: 15.89,
    size: 'L',
    harborType: 'LC',
    unlocode: 'ITGIT',
    channelDepthFt: 17,
    rail: 'Y',
  },
  {
    id: 'wpi:33490',
    name: 'Glasgow',
    country: 'GB',
    lat: 55.8667,
    lon: -4.2833,
    size: 'M',
    harborType: 'RT',
    unlocode: 'GBGLW',
    channelDepthFt: 6,
    rail: 'Y',
  },
  {
    id: 'wpi:33390',
    name: 'Greenock',
    country: 'GB',
    lat: 55.95,
    lon: -4.75,
    size: 'M',
    harborType: 'CN',
    unlocode: 'GBGRK',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:31640',
    name: 'Grimsby',
    country: 'GB',
    lat: 53.5833,
    lon: -0.0667,
    size: 'M',
    harborType: 'RT',
    unlocode: 'GBGSY',
    channelDepthFt: 6,
    rail: 'Y',
  },
  {
    id: 'wpi:57830',
    name: 'Guangzhou',
    country: 'CN',
    lat: 23.1167,
    lon: 113.2333,
    size: 'M',
    harborType: 'RN',
    unlocode: 'CNGGZ',
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:45080',
    name: 'Haifa',
    country: 'IL',
    lat: 32.8167,
    lon: 35,
    size: 'M',
    harborType: 'CB',
    unlocode: 'ILHFA',
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:62430',
    name: 'Hakata',
    country: 'JP',
    lat: 33.6,
    lon: 130.4,
    size: 'M',
    harborType: 'CB',
    unlocode: 'JPHKT',
    channelDepthFt: 14,
    rail: 'Y',
  },
  {
    id: 'wpi:61190',
    name: 'Hakodate Ko',
    country: 'JP',
    lat: 41.7833,
    lon: 140.7167,
    size: 'M',
    harborType: 'CB',
    unlocode: 'JPHKD',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:6340',
    name: 'Halifax',
    country: 'CA',
    lat: 44.65,
    lon: -63.5833,
    size: 'L',
    harborType: 'CN',
    unlocode: 'CAHAL',
    channelDepthFt: 20,
    rail: 'Y',
  },
  {
    id: 'wpi:30780',
    name: 'Hamburg',
    country: 'DE',
    lat: 53.55,
    lon: 9.9333,
    size: 'L',
    harborType: 'LC',
    unlocode: 'DEHAM',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:3050',
    name: 'Hamilton',
    country: 'CA',
    lat: 43.25,
    lon: -79.85,
    size: 'M',
    harborType: 'CN',
    unlocode: 'CAHAM',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:60060',
    name: 'Hankow',
    country: 'CN',
    lat: 30.5833,
    lon: 114.2833,
    size: 'M',
    harborType: 'RN',
    unlocode: 'CNHNK',
    channelDepthFt: 3,
    rail: 'Y',
  },
  {
    id: 'wpi:21610',
    name: 'Harstad',
    country: 'NO',
    lat: 68.8,
    lon: 16.55,
    size: 'M',
    harborType: 'CN',
    unlocode: 'NOHRD',
    channelDepthFt: 23,
    rail: 'U',
  },
  {
    id: 'wpi:44540',
    name: 'Haydarpasa',
    country: 'TR',
    lat: 41,
    lon: 29.0167,
    size: 'M',
    harborType: 'CB',
    unlocode: 'TRHAY',
    channelDepthFt: 23,
    rail: 'Y',
  },
  {
    id: 'wpi:61568',
    name: 'Higashi-Harima',
    country: 'JP',
    lat: 34.7,
    lon: 134.8333,
    size: 'M',
    harborType: 'CB',
    unlocode: 'JPHHR',
    channelDepthFt: 14,
    rail: 'U',
  },
  {
    id: 'wpi:56090',
    name: 'Hilo',
    country: 'US',
    lat: 19.7333,
    lon: -155.0667,
    size: 'M',
    harborType: 'CB',
    unlocode: 'USITO',
    channelDepthFt: 9,
    rail: 'U',
  },
  {
    id: 'wpi:61567',
    name: 'Himeji',
    country: 'JP',
    lat: 34.75,
    lon: 134.6333,
    size: 'M',
    harborType: 'CB',
    unlocode: 'JPHIM',
    channelDepthFt: 16,
    rail: 'Y',
  },
  {
    id: 'wpi:61650',
    name: 'Hiroshima',
    country: 'JP',
    lat: 34.35,
    lon: 132.4667,
    size: 'M',
    harborType: 'OR',
    unlocode: 'JPHIJ',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:54760',
    name: 'Hobart',
    country: 'AU',
    lat: -42.8833,
    lon: 147.3333,
    size: 'M',
    harborType: 'RN',
    unlocode: 'AUHBA',
    channelDepthFt: 13,
    rail: 'U',
  },
  {
    id: 'wpi:7770',
    name: 'Hoboken',
    country: 'US',
    lat: 40.75,
    lon: -74.0167,
    size: 'M',
    harborType: 'RN',
    unlocode: 'USHBK',
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:57840',
    name: 'Hong Kong',
    country: 'HK',
    lat: 22.2667,
    lon: 114.2,
    size: 'L',
    harborType: 'CN',
    unlocode: 'HKHKG',
    channelDepthFt: 14,
    rail: 'Y',
  },
  {
    id: 'wpi:56280',
    name: 'Honolulu',
    country: 'US',
    lat: 21.3,
    lon: -157.8667,
    size: 'M',
    harborType: 'CB',
    unlocode: 'USHNL',
    channelDepthFt: 11,
    rail: 'U',
  },
  {
    id: 'wpi:9240',
    name: 'Houston',
    country: 'US',
    lat: 29.75,
    lon: -95.2833,
    size: 'L',
    harborType: 'RT',
    unlocode: 'USHOU',
    channelDepthFt: 14,
    rail: 'Y',
  },
  {
    id: 'wpi:57910',
    name: 'Hua-Lien Kang',
    country: 'TW',
    lat: 23.9833,
    lon: 121.6,
    size: 'M',
    harborType: 'CB',
    unlocode: 'TWHUN',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:38220',
    name: 'Huelva',
    country: 'ES',
    lat: 37.25,
    lon: -6.95,
    size: 'M',
    harborType: 'RN',
    unlocode: 'ESHUV',
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:43645',
    name: 'Illichivsk',
    country: 'UA',
    lat: 46.3,
    lon: 30.65,
    size: 'L',
    harborType: 'CB',
    unlocode: 'UAILK',
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:31650',
    name: 'Immingham',
    country: 'GB',
    lat: 53.6333,
    lon: -0.2,
    size: 'M',
    harborType: 'RT',
    unlocode: 'GBIMM',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:60320',
    name: 'Inchon',
    country: 'KR',
    lat: 37.4667,
    lon: 126.6167,
    size: 'L',
    harborType: 'RB',
    unlocode: 'KRINC',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:4780',
    name: 'Indiana Harbor',
    country: 'US',
    lat: 41.6667,
    lon: -87.4333,
    size: 'M',
    harborType: 'CB',
    unlocode: 'USECH',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:43130',
    name: 'Iraklion',
    country: 'GR',
    lat: 35.35,
    lon: 25.15,
    size: 'M',
    harborType: 'CB',
    unlocode: 'GRHER',
    channelDepthFt: 8,
    rail: 'U',
  },
  {
    id: 'wpi:9950',
    name: 'Ireland Island',
    country: 'BM',
    lat: 32.3167,
    lon: -64.8333,
    size: 'M',
    harborType: 'CB',
    unlocode: 'BMFPT',
    channelDepthFt: 8,
    rail: 'U',
  },
  {
    id: 'wpi:61245',
    name: 'Ishikari Bay New Port',
    country: 'JP',
    lat: 43.2167,
    lon: 141.2833,
    size: 'M',
    harborType: 'CB',
    unlocode: 'JPISI',
    channelDepthFt: 9,
    rail: 'U',
  },
  {
    id: 'wpi:43420',
    name: 'Istanbul',
    country: 'TR',
    lat: 41.0167,
    lon: 28.9667,
    size: 'L',
    harborType: 'LC',
    unlocode: 'TRIST',
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:13020',
    name: 'Itajai',
    country: 'BR',
    lat: -26.9167,
    lon: -48.6333,
    size: 'M',
    harborType: 'RN',
    unlocode: 'BRITJ',
    channelDepthFt: 9,
    rail: 'U',
  },
  {
    id: 'wpi:61662',
    name: 'Iwakuni Ko',
    country: 'JP',
    lat: 34.1833,
    lon: 132.25,
    size: 'M',
    harborType: 'OR',
    unlocode: 'JPIWK',
    channelDepthFt: 22,
    rail: 'Y',
  },
  {
    id: 'wpi:44750',
    name: 'Izmir',
    country: 'TR',
    lat: 38.4333,
    lon: 27.1333,
    size: 'L',
    harborType: 'CN',
    unlocode: 'TRIZM',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:48282',
    name: 'Jabal Az Zannah/ruways',
    country: 'AE',
    lat: 24.2,
    lon: 52.7,
    size: 'M',
    harborType: 'CB',
    unlocode: 'AEJED',
    channelDepthFt: 14,
    rail: 'U',
  },
  {
    id: 'wpi:8580',
    name: 'Jacksonville',
    country: 'US',
    lat: 30.3167,
    lon: -81.65,
    size: 'M',
    harborType: 'RN',
    unlocode: 'USJAX',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:50970',
    name: 'Jakarta',
    country: 'ID',
    lat: -6.1,
    lon: 106.8833,
    size: 'L',
    harborType: 'CB',
    unlocode: 'IDJKT',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:46690',
    name: 'Jamestown',
    country: 'SH',
    lat: -15.9167,
    lon: -5.7167,
    size: 'L',
    harborType: 'OR',
    unlocode: 'SHSHN',
    channelDepthFt: 23,
    rail: 'U',
  },
  {
    id: 'wpi:7780',
    name: 'Jersey City',
    country: 'US',
    lat: 40.7167,
    lon: -74.0333,
    size: 'M',
    harborType: 'RN',
    unlocode: 'USJEC',
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:49982',
    name: 'Johor',
    country: 'MY',
    lat: 1.4333,
    lon: 103.9,
    size: 'L',
    harborType: 'RN',
    unlocode: 'MYJHB',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:50017',
    name: 'Jurong Island',
    country: 'SG',
    lat: 1.2833,
    lon: 103.7333,
    size: 'L',
    harborType: 'CN',
    unlocode: 'SGJUR',
    channelDepthFt: 14,
    rail: 'U',
  },
  {
    id: 'wpi:62220',
    name: 'Kagoshima Ko',
    country: 'JP',
    lat: 31.5833,
    lon: 130.5667,
    size: 'M',
    harborType: 'CN',
    unlocode: 'JPKOJ',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:28690',
    name: 'Kaliningrad',
    country: 'RU',
    lat: 54.7,
    lon: 20.4833,
    size: 'M',
    harborType: 'RB',
    unlocode: 'RUKGD',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:57485',
    name: 'Kampong Saom',
    country: 'KH',
    lat: 10.6333,
    lon: 103.5,
    size: 'M',
    harborType: 'CB',
    unlocode: 'KHKOS',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:57920',
    name: 'Kao-Hsiung',
    country: 'TW',
    lat: 22.6167,
    lon: 120.25,
    size: 'M',
    harborType: 'CB',
    unlocode: 'TWKHH',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:48600',
    name: 'Karachi',
    country: 'PK',
    lat: 24.7833,
    lon: 66.9833,
    size: 'M',
    harborType: 'CN',
    unlocode: 'PKKHI',
    channelDepthFt: 16,
    rail: 'Y',
  },
  {
    id: 'wpi:23451',
    name: 'Karsto',
    country: 'NO',
    lat: 59.2667,
    lon: 5.5167,
    size: 'M',
    harborType: 'OR',
    unlocode: 'NOKAR',
    channelDepthFt: 23,
    rail: 'U',
  },
  {
    id: 'wpi:53045',
    name: 'Kasim Terminal',
    country: 'ID',
    lat: -1.3,
    lon: 131.0167,
    size: 'L',
    harborType: 'OR',
    unlocode: 'IDKAS',
    channelDepthFt: 16,
    rail: 'U',
  },
  {
    id: 'wpi:61385',
    name: 'Kawasaki Ko',
    country: 'JP',
    lat: 35.5,
    lon: 139.7667,
    size: 'L',
    harborType: 'CB',
    unlocode: 'JPKWS',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:50000',
    name: 'Keppel - (East Singapore)',
    country: 'SG',
    lat: 1.2833,
    lon: 103.85,
    size: 'L',
    harborType: 'CN',
    unlocode: 'SGKEP',
    channelDepthFt: 13,
    rail: 'U',
  },
  {
    id: 'wpi:41720',
    name: 'Kerkira',
    country: 'GR',
    lat: 39.6167,
    lon: 19.9333,
    size: 'M',
    harborType: 'OR',
    unlocode: 'GRCFU',
    channelDepthFt: 8,
    rail: 'U',
  },
  {
    id: 'wpi:48327',
    name: 'Khalifa Bin Salman',
    country: 'BH',
    lat: 26.25,
    lon: 50.75,
    size: 'M',
    harborType: 'CB',
    unlocode: 'BHKBS',
    channelDepthFt: 14,
    rail: 'U',
  },
  {
    id: 'wpi:48263',
    name: 'Khawr Fakkan',
    country: 'AE',
    lat: 25.3628,
    lon: 56.3689,
    size: 'M',
    harborType: 'CN',
    unlocode: 'AEKLF',
    channelDepthFt: 16,
    rail: 'U',
  },
  {
    id: 'wpi:48420',
    name: 'Khorramshahr',
    country: 'IR',
    lat: 30.4333,
    lon: 48.1833,
    size: 'M',
    harborType: 'RN',
    unlocode: 'IRKHO',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:31660',
    name: 'Kingston Upon Hull',
    country: 'GB',
    lat: 53.75,
    lon: -0.2833,
    size: 'M',
    harborType: 'RT',
    unlocode: 'GBHUL',
    channelDepthFt: 5,
    rail: 'Y',
  },
  {
    id: 'wpi:61560',
    name: 'Kobe',
    country: 'JP',
    lat: 34.65,
    lon: 135.1833,
    size: 'L',
    harborType: 'OR',
    unlocode: 'JPUKB',
    channelDepthFt: 14,
    rail: 'Y',
  },
  {
    id: 'wpi:61970',
    name: 'Kochi Ko',
    country: 'JP',
    lat: 33.5,
    lon: 133.5667,
    size: 'M',
    harborType: 'CN',
    unlocode: 'JPKCZ',
    channelDepthFt: 8,
    rail: 'U',
  },
  {
    id: 'wpi:51690',
    name: 'Kota Kinabalu',
    country: 'MY',
    lat: 5.9833,
    lon: 116.0667,
    size: 'M',
    harborType: 'CN',
    unlocode: 'MYBKI',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:61640',
    name: 'Kure',
    country: 'JP',
    lat: 34.2333,
    lon: 132.55,
    size: 'M',
    harborType: 'CN',
    unlocode: 'JPKRE',
    channelDepthFt: 17,
    rail: 'Y',
  },
  {
    id: 'wpi:61160',
    name: 'Kushiro Ko',
    country: 'JP',
    lat: 42.9833,
    lon: 144.3667,
    size: 'M',
    harborType: 'CB',
    unlocode: 'JPKUH',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:45420',
    name: 'La Goulette',
    country: 'TN',
    lat: 36.8,
    lon: 10.3,
    size: 'M',
    harborType: 'CB',
    unlocode: 'TNLGN',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:37000',
    name: 'La Pallice',
    country: 'FR',
    lat: 46.1667,
    lon: -1.2167,
    size: 'M',
    harborType: 'CT',
    unlocode: 'FRLPE',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:13770',
    name: 'La Plata',
    country: 'AR',
    lat: -34.8333,
    lon: -57.8833,
    size: 'M',
    harborType: 'RB',
    unlocode: 'ARLPG',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:37010',
    name: 'La Rochelle',
    country: 'FR',
    lat: 46.15,
    lon: -1.15,
    size: 'M',
    harborType: 'CT',
    unlocode: 'FRLRH',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:39520',
    name: 'La Spezia',
    country: 'IT',
    lat: 44.1,
    lon: 9.8333,
    size: 'L',
    harborType: 'CB',
    unlocode: 'ITSPE',
    channelDepthFt: 14,
    rail: 'Y',
  },
  {
    id: 'wpi:38010',
    name: 'Lagos',
    country: 'PT',
    lat: 37.1,
    lon: -8.6167,
    size: 'L',
    harborType: null,
    unlocode: 'PTLOS',
    channelDepthFt: 0,
    rail: 'U',
  },
  {
    id: 'wpi:46130',
    name: 'Lagos',
    country: 'NG',
    lat: 6.4,
    lon: 3.4,
    size: 'L',
    harborType: 'RN',
    unlocode: 'NGLOS',
    channelDepthFt: 14,
    rail: 'Y',
  },
  {
    id: 'wpi:38170',
    name: 'Las Palmas',
    country: 'ES',
    lat: 28.15,
    lon: -15.4167,
    size: 'L',
    harborType: 'CB',
    unlocode: 'ESLPA',
    channelDepthFt: 11,
    rail: 'U',
  },
  {
    id: 'wpi:31930',
    name: 'Leith',
    country: 'GB',
    lat: 55.9833,
    lon: -3.1833,
    size: 'M',
    harborType: 'RT',
    unlocode: 'GBLEI',
    channelDepthFt: 6,
    rail: 'Y',
  },
  {
    id: 'wpi:32600',
    name: 'Lerwick',
    country: 'GB',
    lat: 60.167,
    lon: -1.15,
    size: 'M',
    harborType: 'CN',
    unlocode: 'GBLER',
    channelDepthFt: 9,
    rail: 'N',
  },
  {
    id: 'wpi:36960',
    name: "Les Sables D' Olonne",
    country: 'FR',
    lat: 46.5,
    lon: -1.8,
    size: 'M',
    harborType: 'RB',
    unlocode: 'FRLSO',
    channelDepthFt: 6,
    rail: 'Y',
  },
  {
    id: 'wpi:46430',
    name: 'Libreville',
    country: 'GA',
    lat: 0.3833,
    lon: 9.45,
    size: 'M',
    harborType: 'OR',
    unlocode: 'GALBV',
    channelDepthFt: 2,
    rail: 'Y',
  },
  {
    id: 'wpi:37990',
    name: 'Lisboa',
    country: 'PT',
    lat: 38.7,
    lon: -9.1667,
    size: 'L',
    harborType: 'RN',
    unlocode: 'PTLIS',
    channelDepthFt: 14,
    rail: 'Y',
  },
  {
    id: 'wpi:34690',
    name: 'Liverpool',
    country: 'GB',
    lat: 53.4167,
    lon: -3,
    size: 'L',
    harborType: 'RT',
    unlocode: 'GBLIV',
    channelDepthFt: 6,
    rail: 'Y',
  },
  {
    id: 'wpi:39590',
    name: 'Livorno',
    country: 'IT',
    lat: 43.542,
    lon: 10.29,
    size: 'L',
    harborType: 'CB',
    unlocode: 'ITLIV',
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:57775',
    name: 'Lon Shui Terminal',
    country: 'CN',
    lat: 20.8333,
    lon: 115.6833,
    size: 'L',
    harborType: 'OR',
    unlocode: null,
    channelDepthFt: 23,
    rail: 'U',
  },
  {
    id: 'wpi:31470',
    name: 'London',
    country: 'GB',
    lat: 51.5,
    lon: -0.0833,
    size: 'L',
    harborType: 'RB',
    unlocode: 'GBLON',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:33830',
    name: 'Londonderry',
    country: 'GB',
    lat: 55,
    lon: -7.3167,
    size: 'M',
    harborType: 'RN',
    unlocode: 'GBLDY',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:16070',
    name: 'Long Beach',
    country: 'US',
    lat: 33.7667,
    lon: -118.1833,
    size: 'M',
    harborType: 'CB',
    unlocode: 'USLGB',
    channelDepthFt: 19,
    rail: 'Y',
  },
  {
    id: 'wpi:8980',
    name: 'Loop Terminal',
    country: 'US',
    lat: 28.8833,
    lon: -90.0167,
    size: 'L',
    harborType: 'OR',
    unlocode: 'USLO9',
    channelDepthFt: 23,
    rail: 'U',
  },
  {
    id: 'wpi:36680',
    name: 'Lorient',
    country: 'FR',
    lat: 47.75,
    lon: -3.35,
    size: 'M',
    harborType: 'RN',
    unlocode: 'FRLRT',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:16080',
    name: 'Los Angeles',
    country: 'US',
    lat: 33.75,
    lon: -118.25,
    size: 'L',
    harborType: 'CB',
    unlocode: 'USLAX',
    channelDepthFt: 14,
    rail: 'Y',
  },
  {
    id: 'wpi:32490',
    name: 'Lyness',
    country: 'GB',
    lat: 58.8333,
    lon: -3.2,
    size: 'M',
    harborType: 'CN',
    unlocode: 'GBLYS',
    channelDepthFt: 13,
    rail: 'U',
  },
  {
    id: 'wpi:57810',
    name: 'Macau',
    country: 'MO',
    lat: 22.1833,
    lon: 113.5667,
    size: 'M',
    harborType: 'CB',
    unlocode: 'MOMFM',
    channelDepthFt: 3,
    rail: 'U',
  },
  {
    id: 'wpi:38370',
    name: 'Malaga',
    country: 'ES',
    lat: 36.7167,
    lon: -4.4167,
    size: 'M',
    harborType: 'CB',
    unlocode: 'ESAGP',
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:34700',
    name: 'Manchester',
    country: 'GB',
    lat: 53.4833,
    lon: -2.2667,
    size: 'L',
    harborType: 'RT',
    unlocode: 'GBMNC',
    channelDepthFt: 5,
    rail: 'Y',
  },
  {
    id: 'wpi:58370',
    name: 'Manila',
    country: 'PH',
    lat: 14.5833,
    lon: 120.9667,
    size: 'L',
    harborType: 'CB',
    unlocode: 'PHMNL',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:55230',
    name: 'Manukau Harbor',
    country: 'NZ',
    lat: -36.9333,
    lon: 174.7833,
    size: 'M',
    harborType: 'CN',
    unlocode: 'NZMCY',
    channelDepthFt: 3,
    rail: 'U',
  },
  {
    id: 'wpi:15770',
    name: 'Manzanillo',
    country: 'MX',
    lat: 19.05,
    lon: -104.3167,
    size: 'M',
    harborType: 'CB',
    unlocode: 'MXZLO',
    channelDepthFt: 16,
    rail: 'Y',
  },
  {
    id: 'wpi:46870',
    name: 'Maputo',
    country: 'MZ',
    lat: -25.9628,
    lon: 32.5447,
    size: 'M',
    harborType: 'LC',
    unlocode: 'MZMPM',
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:60380',
    name: 'Masan',
    country: 'KR',
    lat: 35.1833,
    lon: 128.5667,
    size: 'M',
    harborType: 'CN',
    unlocode: 'KRMAS',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:15810',
    name: 'Mazatlan',
    country: 'MX',
    lat: 23.2,
    lon: -106.4167,
    size: 'M',
    harborType: 'RN',
    unlocode: 'MXMZT',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:50922',
    name: 'Merak Mas Terminal',
    country: 'ID',
    lat: -5.9192,
    lon: 105.9972,
    size: 'M',
    harborType: 'CN',
    unlocode: 'IDMRK',
    channelDepthFt: 11,
    rail: 'U',
  },
  {
    id: 'wpi:44860',
    name: 'Mersin',
    country: 'TR',
    lat: 36.8,
    lon: 34.6333,
    size: 'M',
    harborType: 'CB',
    unlocode: 'TRMER',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:40100',
    name: 'Messina',
    country: 'IT',
    lat: 38.2,
    lon: 15.5667,
    size: 'L',
    harborType: 'CB',
    unlocode: 'ITMSN',
    channelDepthFt: 23,
    rail: 'Y',
  },
  {
    id: 'wpi:61465',
    name: 'Mikawa',
    country: 'JP',
    lat: 34.7167,
    lon: 137.3,
    size: 'L',
    harborType: 'CB',
    unlocode: 'JPMKW',
    channelDepthFt: 11,
    rail: 'U',
  },
  {
    id: 'wpi:40110',
    name: 'Milazzo',
    country: 'IT',
    lat: 38.2167,
    lon: 15.25,
    size: 'M',
    harborType: 'OR',
    unlocode: 'ITMLZ',
    channelDepthFt: 9,
    rail: 'N',
  },
  {
    id: 'wpi:34880',
    name: 'Milford Haven',
    country: 'GB',
    lat: 51.7167,
    lon: -5.0333,
    size: 'M',
    harborType: 'RN',
    unlocode: 'GBMLF',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:4860',
    name: 'Milwaukee',
    country: 'US',
    lat: 43.0333,
    lon: -87.8833,
    size: 'M',
    harborType: 'RN',
    unlocode: 'USMKE',
    channelDepthFt: 6,
    rail: 'Y',
  },
  {
    id: 'wpi:48361',
    name: 'Mina Al Ahmadi',
    country: 'KW',
    lat: 29.0667,
    lon: 48.1667,
    size: 'M',
    harborType: 'OR',
    unlocode: 'KWMEA',
    channelDepthFt: 16,
    rail: 'U',
  },
  {
    id: 'wpi:48357',
    name: 'Mina Ash Shuaybah',
    country: 'KW',
    lat: 29.0333,
    lon: 48.1667,
    size: 'M',
    harborType: 'OR',
    unlocode: 'KWSAA',
    channelDepthFt: 14,
    rail: 'U',
  },
  {
    id: 'wpi:48325',
    name: 'Mina Salman',
    country: 'BH',
    lat: 26.2,
    lon: 50.6333,
    size: 'M',
    harborType: 'CN',
    unlocode: 'BHMIN',
    channelDepthFt: 14,
    rail: 'Y',
  },
  {
    id: 'wpi:45330',
    name: 'Mina Tarabulus (Tripoli)',
    country: 'LY',
    lat: 32.9,
    lon: 13.1833,
    size: 'M',
    harborType: 'CB',
    unlocode: 'LYTIP',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:61790',
    name: 'Miyazu',
    country: 'JP',
    lat: 35.5333,
    lon: 135.2,
    size: 'M',
    harborType: 'CN',
    unlocode: 'JPMIY',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:61595',
    name: 'Mizushima Ko',
    country: 'JP',
    lat: 34.5,
    lon: 133.75,
    size: 'M',
    harborType: 'CN',
    unlocode: 'JPMIZ',
    channelDepthFt: 14,
    rail: 'Y',
  },
  {
    id: 'wpi:8770',
    name: 'Mobile',
    country: 'US',
    lat: 30.6833,
    lon: -88.1167,
    size: 'L',
    harborType: 'RN',
    unlocode: 'USMOB',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:62140',
    name: 'Moji Ko',
    country: 'JP',
    lat: 33.95,
    lon: 130.9667,
    size: 'M',
    harborType: 'RN',
    unlocode: 'JPMOJ',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:60340',
    name: 'Mokpo',
    country: 'KR',
    lat: 34.7833,
    lon: 126.3833,
    size: 'M',
    harborType: 'RN',
    unlocode: 'KRMOK',
    channelDepthFt: 22,
    rail: 'Y',
  },
  {
    id: 'wpi:47100',
    name: 'Mombasa',
    country: 'KE',
    lat: -4.0667,
    lon: 39.6667,
    size: 'M',
    harborType: 'CT',
    unlocode: 'KEMBA',
    channelDepthFt: 14,
    rail: 'Y',
  },
  {
    id: 'wpi:40790',
    name: 'Monfalcone',
    country: 'IT',
    lat: 45.7833,
    lon: 13.55,
    size: 'M',
    harborType: 'RB',
    unlocode: 'ITMNF',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:13120',
    name: 'Montevideo',
    country: 'UY',
    lat: -34.9,
    lon: -56.2167,
    size: 'M',
    harborType: 'CB',
    unlocode: 'UYMVD',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:36855',
    name: 'Montoir',
    country: 'FR',
    lat: 47.3,
    lon: -2.1333,
    size: 'M',
    harborType: 'RN',
    unlocode: 'FRMTX',
    channelDepthFt: 13,
    rail: 'U',
  },
  {
    id: 'wpi:2235',
    name: 'Montreal',
    country: 'CA',
    lat: 45.5167,
    lon: -73.55,
    size: 'L',
    harborType: 'RN',
    unlocode: 'CAMTR',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:46800',
    name: 'Mossel Bay',
    country: 'ZA',
    lat: -34.1747,
    lon: 22.1461,
    size: 'M',
    harborType: 'CB',
    unlocode: 'ZAMZY',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:47160',
    name: 'Muqdisho',
    country: 'SO',
    lat: 2.0333,
    lon: 45.35,
    size: 'L',
    harborType: 'CB',
    unlocode: 'SOMGQ',
    channelDepthFt: 11,
    rail: 'U',
  },
  {
    id: 'wpi:62950',
    name: 'Murmansk',
    country: 'RU',
    lat: 68.9833,
    lon: 33.05,
    size: 'L',
    harborType: 'RN',
    unlocode: 'RUMMK',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:61170',
    name: 'Muroran Ko',
    country: 'JP',
    lat: 42.35,
    lon: 140.9667,
    size: 'M',
    harborType: 'CN',
    unlocode: 'JPMUR',
    channelDepthFt: 16,
    rail: 'Y',
  },
  {
    id: 'wpi:62360',
    name: 'Nagasaki',
    country: 'JP',
    lat: 32.7167,
    lon: 129.85,
    size: 'L',
    harborType: 'CN',
    unlocode: 'JPNGS',
    channelDepthFt: 13,
    rail: 'U',
  },
  {
    id: 'wpi:61480',
    name: 'Nagoya Ko',
    country: 'JP',
    lat: 35.0667,
    lon: 136.8667,
    size: 'L',
    harborType: 'CB',
    unlocode: 'JPNGO',
    channelDepthFt: 16,
    rail: 'Y',
  },
  {
    id: 'wpi:36900',
    name: 'Nantes',
    country: 'FR',
    lat: 47.2,
    lon: -1.5667,
    size: 'M',
    harborType: 'RN',
    unlocode: 'FRNTE',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:39960',
    name: 'Napoli',
    country: 'IT',
    lat: 40.833,
    lon: 14.275,
    size: 'L',
    harborType: 'CB',
    unlocode: 'ITNAP',
    channelDepthFt: 14,
    rail: 'Y',
  },
  {
    id: 'wpi:44752',
    name: 'Nemrut Limani Bay',
    country: 'TR',
    lat: 38.7667,
    lon: 26.9167,
    size: 'M',
    harborType: 'CB',
    unlocode: 'TRNEM',
    channelDepthFt: 16,
    rail: 'U',
  },
  {
    id: 'wpi:8860',
    name: 'New Orleans',
    country: 'US',
    lat: 29.95,
    lon: -90.05,
    size: 'L',
    harborType: 'RN',
    unlocode: 'USMSY',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:18100',
    name: 'New Westminster',
    country: 'CA',
    lat: 49.2,
    lon: -122.9167,
    size: 'M',
    harborType: 'RN',
    unlocode: 'CANWE',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:7640',
    name: 'New York City',
    country: 'US',
    lat: 40.7,
    lon: -74.0167,
    size: 'L',
    harborType: 'RN',
    unlocode: 'USNYC',
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:7810',
    name: 'Newark',
    country: 'US',
    lat: 40.7,
    lon: -74.15,
    size: 'M',
    harborType: 'RB',
    unlocode: 'USEWR',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:35015',
    name: 'Newport',
    country: 'GB',
    lat: 51.55,
    lon: -2.9833,
    size: 'M',
    harborType: 'RT',
    unlocode: 'GBNPT',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:8300',
    name: 'Newport News',
    country: 'US',
    lat: 36.9667,
    lon: -76.4333,
    size: 'M',
    harborType: 'CN',
    unlocode: 'USNNS',
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:61870',
    name: 'Niigata Ko',
    country: 'JP',
    lat: 37.9167,
    lon: 139.05,
    size: 'M',
    harborType: 'RB',
    unlocode: 'JPKIJ',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:8280',
    name: 'Norfolk',
    country: 'US',
    lat: 36.85,
    lon: -76.3,
    size: 'L',
    harborType: 'RN',
    unlocode: 'USORF',
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:25190',
    name: 'Norrkoping',
    country: 'SE',
    lat: 58.5833,
    lon: 16.2,
    size: 'M',
    harborType: 'RN',
    unlocode: 'SENRK',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:45812',
    name: 'Nouadhibou',
    country: 'MR',
    lat: 20.9167,
    lon: -17.05,
    size: 'M',
    harborType: 'CN',
    unlocode: 'MRNDB',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:44200',
    name: 'Novorossiysk',
    country: 'RU',
    lat: 44.7167,
    lon: 37.7833,
    size: 'L',
    harborType: 'CB',
    unlocode: 'RUNVS',
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:16340',
    name: 'Oakland',
    country: 'US',
    lat: 37.8167,
    lon: -122.3333,
    size: 'L',
    harborType: 'CN',
    unlocode: 'USOAK',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:43650',
    name: 'Odesa',
    country: 'UA',
    lat: 46.4833,
    lon: 30.7333,
    size: 'L',
    harborType: 'CB',
    unlocode: 'UAODS',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:61630',
    name: 'Onomichi-Itozaki',
    country: 'JP',
    lat: 34.3833,
    lon: 133.1667,
    size: 'L',
    harborType: 'CN',
    unlocode: 'JPONX',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:45640',
    name: 'Oran',
    country: 'DZ',
    lat: 35.7,
    lon: -0.6333,
    size: 'L',
    harborType: 'CB',
    unlocode: 'DZORN',
    channelDepthFt: 23,
    rail: 'Y',
  },
  {
    id: 'wpi:42340',
    name: 'Ormos Aliveriou',
    country: 'GR',
    lat: 38.3833,
    lon: 24.05,
    size: 'M',
    harborType: 'CB',
    unlocode: 'GRLVR',
    channelDepthFt: 11,
    rail: 'U',
  },
  {
    id: 'wpi:61550',
    name: 'Osaka',
    country: 'JP',
    lat: 34.65,
    lon: 135.4333,
    size: 'L',
    harborType: 'CB',
    unlocode: 'JPOSA',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:61230',
    name: 'Otaru Ko',
    country: 'JP',
    lat: 43.2,
    lon: 141.0167,
    size: 'M',
    harborType: 'CB',
    unlocode: 'JPOTR',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:50330',
    name: 'Palembang',
    country: 'ID',
    lat: -2.9833,
    lon: 104.7667,
    size: 'M',
    harborType: 'RN',
    unlocode: 'IDPLM',
    channelDepthFt: 3,
    rail: 'Y',
  },
  {
    id: 'wpi:38630',
    name: 'Palma De Mallorca',
    country: 'ES',
    lat: 39.5667,
    lon: 2.6333,
    size: 'M',
    harborType: 'CB',
    unlocode: 'ESPMI',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:32230',
    name: 'Peterhead',
    country: 'GB',
    lat: 57.5,
    lon: -1.7833,
    size: 'M',
    harborType: 'CB',
    unlocode: 'GBPHD',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:8110',
    name: 'Philadelphia',
    country: 'US',
    lat: 39.95,
    lon: -75.1333,
    size: 'L',
    harborType: 'RN',
    unlocode: 'USPHL',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:42230',
    name: 'Piraievs',
    country: 'GR',
    lat: 37.9333,
    lon: 23.65,
    size: 'L',
    harborType: 'CB',
    unlocode: 'GRPIR',
    channelDepthFt: 23,
    rail: 'Y',
  },
  {
    id: 'wpi:11270',
    name: 'Playa De Guayanilla',
    country: 'PR',
    lat: 18.0167,
    lon: -66.7667,
    size: 'M',
    harborType: 'CB',
    unlocode: 'PRGUY',
    channelDepthFt: 9,
    rail: 'U',
  },
  {
    id: 'wpi:11260',
    name: 'Playa De Ponce',
    country: 'PR',
    lat: 17.9833,
    lon: -66.6167,
    size: 'M',
    harborType: 'CB',
    unlocode: 'PRPSE',
    channelDepthFt: 9,
    rail: 'U',
  },
  {
    id: 'wpi:35370',
    name: 'Plymouth',
    country: 'GB',
    lat: 50.3667,
    lon: -4.15,
    size: 'M',
    harborType: 'CN',
    unlocode: 'GBPLY',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:11450',
    name: 'Pointe A Pitre',
    country: 'GP',
    lat: 16.2333,
    lon: -61.5333,
    size: 'M',
    harborType: 'CN',
    unlocode: 'GPPTP',
    channelDepthFt: 11,
    rail: 'U',
  },
  {
    id: 'wpi:27740',
    name: 'Pori',
    country: 'FI',
    lat: 61.4833,
    lon: 21.8,
    size: 'L',
    harborType: 'CN',
    unlocode: 'FIPOR',
    channelDepthFt: 6,
    rail: 'Y',
  },
  {
    id: 'wpi:54220',
    name: 'Port Adelaide',
    country: 'AU',
    lat: -34.85,
    lon: 138.5,
    size: 'M',
    harborType: 'RN',
    unlocode: 'AUPAE',
    channelDepthFt: 14,
    rail: 'Y',
  },
  {
    id: 'wpi:9080',
    name: 'Port Arthur',
    country: 'US',
    lat: 29.8333,
    lon: -93.9667,
    size: 'M',
    harborType: 'LC',
    unlocode: 'USPOA',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:54940',
    name: 'Port Dalrymple',
    country: 'AU',
    lat: -41.1333,
    lon: 146.8333,
    size: 'M',
    harborType: 'CN',
    unlocode: 'AUPTD',
    channelDepthFt: 9,
    rail: 'U',
  },
  {
    id: 'wpi:12770',
    name: 'Port De Salvador',
    country: 'BR',
    lat: -12.9667,
    lon: -38.5167,
    size: 'M',
    harborType: 'CB',
    unlocode: 'BRSSA',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:49960',
    name: 'Port Dickson',
    country: 'MY',
    lat: 2.5333,
    lon: 101.7833,
    size: 'M',
    harborType: 'OR',
    unlocode: 'MYPDI',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:46820',
    name: 'Port Elizabeth',
    country: 'ZA',
    lat: -33.9519,
    lon: 25.6425,
    size: 'M',
    harborType: 'CB',
    unlocode: 'ZAPLZ',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:8630',
    name: 'Port Everglades',
    country: 'US',
    lat: 26.1,
    lon: -80.1167,
    size: 'M',
    harborType: 'CN',
    unlocode: 'USPEF',
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:46440',
    name: 'Port Gentil',
    country: 'GA',
    lat: -0.7,
    lon: 8.8,
    size: 'M',
    harborType: 'CN',
    unlocode: 'GAPOG',
    channelDepthFt: 14,
    rail: 'Y',
  },
  {
    id: 'wpi:49930',
    name: 'Port Klang',
    country: 'MY',
    lat: 3,
    lon: 101.4,
    size: 'L',
    harborType: 'CN',
    unlocode: 'MYPKG',
    channelDepthFt: 16,
    rail: 'Y',
  },
  {
    id: 'wpi:35840',
    name: 'Port Of Le Havre',
    country: 'FR',
    lat: 49.4833,
    lon: 0.1167,
    size: 'L',
    harborType: 'RT',
    unlocode: 'FRLEH',
    channelDepthFt: 14,
    rail: 'Y',
  },
  {
    id: 'wpi:35850',
    name: 'Port Of Rouen',
    country: 'FR',
    lat: 49.45,
    lon: 1.0667,
    size: 'L',
    harborType: 'RN',
    unlocode: 'FRURO',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:28715',
    name: 'Port Polnochny',
    country: 'PL',
    lat: 54.4,
    lon: 18.7167,
    size: 'M',
    harborType: 'CB',
    unlocode: null,
    channelDepthFt: 17,
    rail: 'Y',
  },
  {
    id: 'wpi:7150',
    name: 'Portland',
    country: 'US',
    lat: 43.6667,
    lon: -70.25,
    size: 'M',
    harborType: 'CN',
    unlocode: 'USPWM',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:16940',
    name: 'Portland',
    country: 'US',
    lat: 45.5167,
    lon: -122.6667,
    size: 'L',
    harborType: 'RN',
    unlocode: 'USPDX',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:35450',
    name: 'Portland Harbour',
    country: 'GB',
    lat: 50.5833,
    lon: -2.4333,
    size: 'M',
    harborType: 'CB',
    unlocode: 'GBPRH',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:13080',
    name: 'Porto Alegre',
    country: 'BR',
    lat: -30.0333,
    lon: -51.2333,
    size: 'M',
    harborType: 'RN',
    unlocode: 'BRPOA',
    channelDepthFt: 5,
    rail: 'Y',
  },
  {
    id: 'wpi:40720',
    name: 'Porto Di Corsini',
    country: 'IT',
    lat: 44.495,
    lon: 12.291,
    size: 'M',
    harborType: 'LC',
    unlocode: 'ITPCS',
    channelDepthFt: 5,
    rail: 'Y',
  },
  {
    id: 'wpi:40760',
    name: 'Porto Di Lido-Venezia',
    country: 'IT',
    lat: 45.4167,
    lon: 12.4333,
    size: 'L',
    harborType: 'CB',
    unlocode: 'ITVCE',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:35600',
    name: 'Portsmouth Harbour',
    country: 'GB',
    lat: 50.8,
    lon: -1.1,
    size: 'M',
    harborType: 'CT',
    unlocode: 'GBME"',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:18950',
    name: 'Prince Rupert',
    country: 'CA',
    lat: 54.3167,
    lon: -130.3333,
    size: 'M',
    harborType: 'CN',
    unlocode: 'CAPRR',
    channelDepthFt: 23,
    rail: 'Y',
  },
  {
    id: 'wpi:7420',
    name: 'Providence',
    country: 'US',
    lat: 41.8,
    lon: -71.4,
    size: 'M',
    harborType: 'RN',
    unlocode: 'USPVD',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:37400',
    name: 'Puerto De Bilbao',
    country: 'ES',
    lat: 43.35,
    lon: -3.05,
    size: 'M',
    harborType: 'CB',
    unlocode: 'ESBIO',
    channelDepthFt: 6,
    rail: 'Y',
  },
  {
    id: 'wpi:37290',
    name: 'Puerto De Pasajes',
    country: 'ES',
    lat: 43.3333,
    lon: -1.9333,
    size: 'M',
    harborType: 'RN',
    unlocode: 'ESPAS',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:14950',
    name: 'Puerto Del Callao',
    country: 'PE',
    lat: -12.05,
    lon: -77.15,
    size: 'M',
    harborType: 'CB',
    unlocode: 'PECLL',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:50010',
    name: 'Pulau Bukom',
    country: 'SG',
    lat: 1.2333,
    lon: 103.7667,
    size: 'M',
    harborType: 'OR',
    unlocode: 'SGPUB',
    channelDepthFt: 9,
    rail: 'U',
  },
  {
    id: 'wpi:49850',
    name: 'Pulau Pinang',
    country: 'MY',
    lat: 5.4167,
    lon: 100.35,
    size: 'M',
    harborType: 'CN',
    unlocode: 'MYPEN',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:60325',
    name: 'Pyeongtaek Hang',
    country: 'KR',
    lat: 37,
    lon: 126.8,
    size: 'M',
    harborType: 'RN',
    unlocode: 'KRPTK',
    channelDepthFt: 22,
    rail: 'U',
  },
  {
    id: 'wpi:60140',
    name: 'Qingdao Gang',
    country: 'CN',
    lat: 36.0333,
    lon: 120.2667,
    size: 'L',
    harborType: 'OR',
    unlocode: 'CNQIN',
    channelDepthFt: 17,
    rail: 'Y',
  },
  {
    id: 'wpi:60200',
    name: 'Qinhuangdao',
    country: 'CN',
    lat: 39.9333,
    lon: 119.6167,
    size: 'M',
    harborType: 'CB',
    unlocode: 'CNSHP',
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:2180',
    name: 'Quebec',
    country: 'CA',
    lat: 46.8167,
    lon: -71.2167,
    size: 'M',
    harborType: 'RN',
    unlocode: 'CAQUE',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:39420',
    name: 'Rada Di Vado',
    country: 'IT',
    lat: 44.265,
    lon: 8.453,
    size: 'M',
    harborType: 'OR',
    unlocode: 'ITVDL',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:36460',
    name: 'Rade De Brest',
    country: 'FR',
    lat: 48.3833,
    lon: -4.5,
    size: 'L',
    harborType: 'CB',
    unlocode: 'FRBES',
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:35950',
    name: 'Rade De Cherbourg',
    country: 'FR',
    lat: 49.65,
    lon: -1.6333,
    size: 'L',
    harborType: 'CT',
    unlocode: 'FRCER',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:48340',
    name: 'Ras  Tannurah',
    country: 'SA',
    lat: 26.6333,
    lon: 50.1667,
    size: 'M',
    harborType: 'OR',
    unlocode: 'SARTA',
    channelDepthFt: 16,
    rail: 'U',
  },
  {
    id: 'wpi:48155',
    name: 'Ras Isa Marine Terminal',
    country: 'YE',
    lat: 15.1333,
    lon: 42.6,
    size: 'L',
    harborType: null,
    unlocode: 'YERAI',
    channelDepthFt: 0,
    rail: 'U',
  },
  {
    id: 'wpi:48297',
    name: 'Ras Laffan',
    country: 'QA',
    lat: 25.9167,
    lon: 51.5833,
    size: 'M',
    harborType: 'CB',
    unlocode: 'QARLF',
    channelDepthFt: 14,
    rail: 'U',
  },
  {
    id: 'wpi:48015',
    name: 'Ras Shukhier',
    country: 'EG',
    lat: 28.1333,
    lon: 33.2833,
    size: 'M',
    harborType: 'OR',
    unlocode: 'EGRSH',
    channelDepthFt: 11,
    rail: 'U',
  },
  {
    id: 'wpi:12730',
    name: 'Recife',
    country: 'BR',
    lat: -8.05,
    lon: -34.8667,
    size: 'M',
    harborType: 'CB',
    unlocode: 'BRREC',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:46855',
    name: 'Richards Bay',
    country: 'ZA',
    lat: -28.81,
    lon: 32.0983,
    size: 'M',
    harborType: 'CB',
    unlocode: 'ZARCB',
    channelDepthFt: 19,
    rail: 'U',
  },
  {
    id: 'wpi:28610',
    name: 'Riga',
    country: 'LV',
    lat: 56.95,
    lon: 24.1,
    size: 'L',
    harborType: 'RN',
    unlocode: 'LVRIX',
    channelDepthFt: 13,
    rail: 'U',
  },
  {
    id: 'wpi:41010',
    name: 'Rijeka Luka',
    country: 'HR',
    lat: 45.3333,
    lon: 14.4333,
    size: 'L',
    harborType: 'RB',
    unlocode: 'HRRJK',
    channelDepthFt: 17,
    rail: 'Y',
  },
  {
    id: 'wpi:12920',
    name: 'Rio De Janeiro',
    country: 'BR',
    lat: -22.9,
    lon: -43.1667,
    size: 'L',
    harborType: 'CN',
    unlocode: 'BRRIO',
    channelDepthFt: 16,
    rail: 'Y',
  },
  {
    id: 'wpi:13060',
    name: 'Rio Grande',
    country: 'BR',
    lat: -32.05,
    lon: -52.0833,
    size: 'L',
    harborType: 'RN',
    unlocode: 'BRRIG',
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:37040',
    name: 'Rochefort',
    country: 'FR',
    lat: 45.9333,
    lon: -0.95,
    size: 'M',
    harborType: 'RT',
    unlocode: 'FRRCO',
    channelDepthFt: 2,
    rail: 'Y',
  },
  {
    id: 'wpi:13630',
    name: 'Rosario',
    country: 'AR',
    lat: -32.95,
    lon: -60.6333,
    size: 'M',
    harborType: 'RN',
    unlocode: 'ARROS',
    channelDepthFt: 6,
    rail: 'Y',
  },
  {
    id: 'wpi:31140',
    name: 'Rotterdam',
    country: 'NL',
    lat: 51.9,
    lon: 4.4833,
    size: 'L',
    harborType: 'RB',
    unlocode: 'NLRTM',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:61547',
    name: 'Sakai-Senboku',
    country: 'JP',
    lat: 34.55,
    lon: 135.4333,
    size: 'M',
    harborType: 'CB',
    unlocode: 'JPSBK',
    channelDepthFt: 16,
    rail: 'Y',
  },
  {
    id: 'wpi:46750',
    name: 'Saldanha Bay',
    country: 'ZA',
    lat: -33.0333,
    lon: 17.9667,
    size: 'M',
    harborType: 'CB',
    unlocode: 'ZASDB',
    channelDepthFt: 23,
    rail: 'Y',
  },
  {
    id: 'wpi:44450',
    name: 'Samsun',
    country: 'TR',
    lat: 41.3,
    lon: 36.35,
    size: 'L',
    harborType: 'CB',
    unlocode: 'TRSSX',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:16010',
    name: 'San Diego',
    country: 'US',
    lat: 32.7167,
    lon: -117.1833,
    size: 'M',
    harborType: 'CN',
    unlocode: 'USSAN',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:58460',
    name: 'San Fernando Harbor',
    country: 'PH',
    lat: 16.6167,
    lon: 120.3167,
    size: 'M',
    harborType: 'OR',
    unlocode: 'PHSFE',
    channelDepthFt: 16,
    rail: 'Y',
  },
  {
    id: 'wpi:16300',
    name: 'San Francisco',
    country: 'US',
    lat: 37.8167,
    lon: -122.4167,
    size: 'L',
    harborType: 'CN',
    unlocode: 'USSFO',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:28370',
    name: 'Sankt-Peterburg',
    country: 'RU',
    lat: 59.9333,
    lon: 30.3,
    size: 'L',
    harborType: 'CB',
    unlocode: 'RULED',
    channelDepthFt: 3,
    rail: 'Y',
  },
  {
    id: 'wpi:38160',
    name: 'Santa Cruz De Tenerife',
    country: 'ES',
    lat: 28.4667,
    lon: -16.2333,
    size: 'M',
    harborType: 'CB',
    unlocode: 'ESSCT',
    channelDepthFt: 11,
    rail: 'U',
  },
  {
    id: 'wpi:37470',
    name: 'Santander',
    country: 'ES',
    lat: 43.4667,
    lon: -3.7833,
    size: 'M',
    harborType: 'RN',
    unlocode: 'ESSDR',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:12970',
    name: 'Santos',
    country: 'BR',
    lat: -23.95,
    lon: -46.3,
    size: 'L',
    harborType: 'CN',
    unlocode: 'BRSSZ',
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:39215',
    name: 'Sarroch Oil Terminal',
    country: 'IT',
    lat: 39.0833,
    lon: 9.0333,
    size: 'M',
    harborType: 'OR',
    unlocode: 'ITPFX',
    channelDepthFt: 22,
    rail: 'U',
  },
  {
    id: 'wpi:62380',
    name: 'Sasebo',
    country: 'JP',
    lat: 33.1667,
    lon: 129.7167,
    size: 'M',
    harborType: 'CN',
    unlocode: 'JPSSB',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:57446',
    name: 'Sattahip',
    country: 'TH',
    lat: 12.6167,
    lon: 100.9167,
    size: 'M',
    harborType: 'CB',
    unlocode: 'THSAT',
    channelDepthFt: 8,
    rail: 'U',
  },
  {
    id: 'wpi:8530',
    name: 'Savannah',
    country: 'US',
    lat: 32.0833,
    lon: -81.0833,
    size: 'M',
    harborType: 'RN',
    unlocode: 'USSAV',
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:17730',
    name: 'Seattle',
    country: 'US',
    lat: 47.6,
    lon: -122.3333,
    size: 'L',
    harborType: 'CN',
    unlocode: 'USSEA',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:1955',
    name: 'Sept Iles',
    country: 'CA',
    lat: 50.2,
    lon: -66.3833,
    size: 'M',
    harborType: 'RN',
    unlocode: 'CASEI',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:43760',
    name: 'Sevastopol',
    country: 'UA',
    lat: 44.6167,
    lon: 33.5333,
    size: 'L',
    harborType: 'CN',
    unlocode: 'UASVP',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:38270',
    name: 'Sevilla',
    country: 'ES',
    lat: 37.3667,
    lon: -6,
    size: 'M',
    harborType: 'LC',
    unlocode: 'ESSVQ',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:59970',
    name: 'Shanghai',
    country: 'CN',
    lat: 31.2167,
    lon: 121.5,
    size: 'L',
    harborType: 'RN',
    unlocode: 'CNSGH',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:57777',
    name: 'Shekou',
    country: 'CN',
    lat: 22.4667,
    lon: 113.8667,
    size: 'M',
    harborType: 'CN',
    unlocode: 'CNSHK',
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:57458',
    name: 'Si Racha',
    country: 'TH',
    lat: 13.1667,
    lon: 100.9167,
    size: 'M',
    harborType: 'OR',
    unlocode: 'THSRI',
    channelDepthFt: 14,
    rail: 'U',
  },
  {
    id: 'wpi:38005',
    name: 'Sines',
    country: 'PT',
    lat: 37.95,
    lon: -8.8667,
    size: 'M',
    harborType: 'CB',
    unlocode: 'PTSIE',
    channelDepthFt: 0,
    rail: 'Y',
  },
  {
    id: 'wpi:40240',
    name: 'Siracusa',
    country: 'IT',
    lat: 37.05,
    lon: 15.2833,
    size: 'L',
    harborType: 'CB',
    unlocode: 'ITSIR',
    channelDepthFt: 23,
    rail: 'Y',
  },
  {
    id: 'wpi:48320',
    name: 'Sitrah',
    country: 'BH',
    lat: 26.1667,
    lon: 50.6667,
    size: 'M',
    harborType: 'OR',
    unlocode: 'BHSIT',
    channelDepthFt: 14,
    rail: 'Y',
  },
  {
    id: 'wpi:43100',
    name: 'Soudha',
    country: 'GR',
    lat: 35.4833,
    lon: 24.1833,
    size: 'M',
    harborType: 'CN',
    unlocode: 'GRSDH',
    channelDepthFt: 14,
    rail: 'U',
  },
  {
    id: 'wpi:35580',
    name: 'Southampton',
    country: 'GB',
    lat: 50.9,
    lon: -1.4,
    size: 'L',
    harborType: 'RB',
    unlocode: 'GBSOU',
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:41320',
    name: 'Split',
    country: 'HR',
    lat: 43.5,
    lon: 16.4333,
    size: 'L',
    harborType: 'CB',
    unlocode: 'HRSPU',
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:11430',
    name: 'St Johns',
    country: 'AG',
    lat: 17.1167,
    lon: -61.85,
    size: 'M',
    harborType: 'OR',
    unlocode: 'AGSJO',
    channelDepthFt: 9,
    rail: 'U',
  },
  {
    id: 'wpi:36850',
    name: 'St Nazaire',
    country: 'FR',
    lat: 47.2833,
    lon: -2.2,
    size: 'M',
    harborType: 'RT',
    unlocode: 'FRSNR',
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:14000',
    name: 'Stanley',
    country: 'FK',
    lat: -51.7,
    lon: -57.8333,
    size: 'M',
    harborType: 'CN',
    unlocode: 'FKPSY',
    channelDepthFt: 8,
    rail: 'U',
  },
  {
    id: 'wpi:25380',
    name: 'Stockholm',
    country: 'SE',
    lat: 59.3333,
    lon: 18.05,
    size: 'L',
    harborType: 'CB',
    unlocode: 'SESTO',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:57900',
    name: 'Su-Ao',
    country: 'TW',
    lat: 24.6,
    lon: 121.8667,
    size: 'M',
    harborType: 'CB',
    unlocode: null,
    channelDepthFt: 14,
    rail: 'Y',
  },
  {
    id: 'wpi:58395',
    name: 'Subic Bay',
    country: 'PH',
    lat: 14.8,
    lon: 120.2667,
    size: 'M',
    harborType: 'CN',
    unlocode: 'PHSFS',
    channelDepthFt: 23,
    rail: 'Y',
  },
  {
    id: 'wpi:31760',
    name: 'Sunderland',
    country: 'GB',
    lat: 54.9167,
    lon: -1.3667,
    size: 'M',
    harborType: 'RT',
    unlocode: 'GBSUN',
    channelDepthFt: 6,
    rail: 'Y',
  },
  {
    id: 'wpi:5450',
    name: 'Superior',
    country: 'US',
    lat: 46.7333,
    lon: -92.0667,
    size: 'M',
    harborType: 'CB',
    unlocode: 'USSUW',
    channelDepthFt: 6,
    rail: 'Y',
  },
  {
    id: 'wpi:51130',
    name: 'Surabaya',
    country: 'ID',
    lat: -7.2,
    lon: 112.7333,
    size: 'M',
    harborType: 'CB',
    unlocode: 'IDSUB',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:6000',
    name: 'Sydney',
    country: 'CA',
    lat: 46.15,
    lon: -60.2,
    size: 'M',
    harborType: 'CN',
    unlocode: 'CASYD',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:28823',
    name: 'Szczecin',
    country: 'PL',
    lat: 53.4167,
    lon: 14.55,
    size: 'M',
    harborType: 'RN',
    unlocode: 'PLSZZ',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:17700',
    name: 'Tacoma',
    country: 'US',
    lat: 47.2833,
    lon: -122.4167,
    size: 'M',
    harborType: 'CN',
    unlocode: 'USTIW',
    channelDepthFt: 23,
    rail: 'Y',
  },
  {
    id: 'wpi:61415',
    name: 'Tagonoura Ko',
    country: 'JP',
    lat: 35.1333,
    lon: 138.7,
    size: 'M',
    harborType: 'RB',
    unlocode: 'JPTGO',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:8670',
    name: 'Tampa',
    country: 'US',
    lat: 27.9167,
    lon: -82.45,
    size: 'M',
    harborType: 'CN',
    unlocode: 'USTPA',
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:45755',
    name: 'Tanger',
    country: 'MA',
    lat: 35.7833,
    lon: -5.8167,
    size: 'M',
    harborType: 'CB',
    unlocode: 'MATNG',
    channelDepthFt: 0,
    rail: 'Y',
  },
  {
    id: 'wpi:45753',
    name: 'Tangier-Mediterranean',
    country: 'MA',
    lat: 35.9,
    lon: -5.5167,
    size: 'L',
    harborType: 'CB',
    unlocode: 'MAPTM',
    channelDepthFt: 0,
    rail: 'U',
  },
  {
    id: 'wpi:51587',
    name: 'Tanjung Pelepas',
    country: 'MY',
    lat: 1.35,
    lon: 103.55,
    size: 'M',
    harborType: 'RB',
    unlocode: 'MYTPP',
    channelDepthFt: 14,
    rail: 'Y',
  },
  {
    id: 'wpi:57425',
    name: 'Tapis Marine Terminal A',
    country: 'MY',
    lat: 5.5167,
    lon: 105.0167,
    size: 'L',
    harborType: 'OR',
    unlocode: 'MYTAT',
    channelDepthFt: 23,
    rail: 'U',
  },
  {
    id: 'wpi:40470',
    name: 'Taranto',
    country: 'IT',
    lat: 40.4667,
    lon: 17.2,
    size: 'L',
    harborType: 'CB',
    unlocode: 'ITTAR',
    channelDepthFt: 14,
    rail: 'Y',
  },
  {
    id: 'wpi:38540',
    name: 'Tarragona',
    country: 'ES',
    lat: 41.1,
    lon: 1.2333,
    size: 'L',
    harborType: 'CB',
    unlocode: 'ESTAR',
    channelDepthFt: 20,
    rail: 'Y',
  },
  {
    id: 'wpi:45435',
    name: 'Tazerka Oil Terminal',
    country: 'TN',
    lat: 36.6,
    lon: 11.6833,
    size: 'M',
    harborType: 'OR',
    unlocode: 'TNTAT',
    channelDepthFt: 23,
    rail: 'U',
  },
  {
    id: 'wpi:31720',
    name: 'Teesport',
    country: 'GB',
    lat: 54.65,
    lon: -1.1333,
    size: 'L',
    harborType: 'RT',
    unlocode: 'GBTEE',
    channelDepthFt: 14,
    rail: 'Y',
  },
  {
    id: 'wpi:31220',
    name: 'Terneuzen',
    country: 'NL',
    lat: 51.35,
    lon: 3.8167,
    size: 'M',
    harborType: 'RT',
    unlocode: 'NLTNZ',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:57580',
    name: 'Thanh Ho Chi Minh',
    country: 'VN',
    lat: 10.7667,
    lon: 106.7167,
    size: 'M',
    harborType: 'RN',
    unlocode: 'VNSGN',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:42530',
    name: 'Thessaloniki',
    country: 'GR',
    lat: 40.6333,
    lon: 22.9333,
    size: 'M',
    harborType: 'CN',
    unlocode: 'GRSKG',
    channelDepthFt: 0,
    rail: 'Y',
  },
  {
    id: 'wpi:5210',
    name: 'Thunder Bay',
    country: 'CA',
    lat: 48.4,
    lon: -89.2333,
    size: 'M',
    harborType: 'CB',
    unlocode: 'CATHU',
    channelDepthFt: 6,
    rail: 'Y',
  },
  {
    id: 'wpi:60190',
    name: 'Tianjin Xin Gang',
    country: 'CN',
    lat: 38.9667,
    lon: 117.8333,
    size: 'L',
    harborType: 'RN',
    unlocode: 'CNTXG',
    channelDepthFt: 14,
    rail: 'Y',
  },
  {
    id: 'wpi:61680',
    name: 'Tokuyama',
    country: 'JP',
    lat: 34.0333,
    lon: 131.8167,
    size: 'M',
    harborType: 'OR',
    unlocode: 'JPTKY',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:61380',
    name: 'Tokyo Ko',
    country: 'JP',
    lat: 35.6667,
    lon: 139.75,
    size: 'L',
    harborType: 'CN',
    unlocode: 'JPTYO',
    channelDepthFt: 16,
    rail: 'Y',
  },
  {
    id: 'wpi:3560',
    name: 'Toledo',
    country: 'US',
    lat: 41.7,
    lon: -83.4667,
    size: 'M',
    harborType: 'RN',
    unlocode: 'USTOL',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:7840',
    name: 'Tompkinsville SI',
    country: 'US',
    lat: 40.6333,
    lon: -74.0667,
    size: 'M',
    harborType: 'CN',
    unlocode: null,
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:3000',
    name: 'Toronto',
    country: 'CA',
    lat: 43.6167,
    lon: -79.3833,
    size: 'M',
    harborType: 'CN',
    unlocode: 'CATOR',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:38870',
    name: 'Toulon',
    country: 'FR',
    lat: 43.1,
    lon: 5.9167,
    size: 'L',
    harborType: 'CB',
    unlocode: 'FRTLN',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:8890',
    name: 'Tri-City Port',
    country: 'US',
    lat: 38.7167,
    lon: -90.2,
    size: 'L',
    harborType: 'RN',
    unlocode: null,
    channelDepthFt: 3,
    rail: 'Y',
  },
  {
    id: 'wpi:40820',
    name: 'Trieste',
    country: 'IT',
    lat: 45.651,
    lon: 13.746,
    size: 'L',
    harborType: 'CB',
    unlocode: 'ITTRS',
    channelDepthFt: 17,
    rail: 'Y',
  },
  {
    id: 'wpi:2210',
    name: 'Trois Rivieres',
    country: 'CA',
    lat: 46.35,
    lon: -72.55,
    size: 'M',
    harborType: 'RN',
    unlocode: 'CATRR',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:12855',
    name: 'Tubarao',
    country: 'BR',
    lat: -20.2833,
    lon: -40.25,
    size: 'L',
    harborType: 'CB',
    unlocode: 'BRTUB',
    channelDepthFt: 22,
    rail: 'Y',
  },
  {
    id: 'wpi:45430',
    name: 'Tunis',
    country: 'TN',
    lat: 36.8,
    lon: 10.25,
    size: 'M',
    harborType: 'LC',
    unlocode: 'TNTUN',
    channelDepthFt: 6,
    rail: 'U',
  },
  {
    id: 'wpi:27820',
    name: 'Turku',
    country: 'FI',
    lat: 60.45,
    lon: 22.2333,
    size: 'M',
    harborType: 'RB',
    unlocode: 'FITKU',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:31765',
    name: 'Tynemouth',
    country: 'GB',
    lat: 55,
    lon: -1.4,
    size: 'M',
    harborType: 'RT',
    unlocode: 'GBTYM',
    channelDepthFt: 8,
    rail: 'Y',
  },
  {
    id: 'wpi:61690',
    name: 'Ube Ko',
    country: 'JP',
    lat: 33.9333,
    lon: 131.2333,
    size: 'M',
    harborType: 'CB',
    unlocode: 'JPUBJ',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:52320',
    name: 'Ujung Pandang',
    country: 'ID',
    lat: -5.1333,
    lon: 119.4,
    size: 'M',
    harborType: 'CB',
    unlocode: 'IDUPG',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:60400',
    name: 'Ulsan',
    country: 'KR',
    lat: 35.45,
    lon: 129.4,
    size: 'M',
    harborType: 'RN',
    unlocode: 'KRUSN',
    channelDepthFt: 19,
    rail: 'Y',
  },
  {
    id: 'wpi:38480',
    name: 'Valencia',
    country: 'ES',
    lat: 39.45,
    lon: -0.3167,
    size: 'M',
    harborType: 'CB',
    unlocode: 'ESVLC',
    channelDepthFt: 16,
    rail: 'Y',
  },
  {
    id: 'wpi:40330',
    name: 'Valletta Harbors',
    country: 'MT',
    lat: 35.9,
    lon: 14.5167,
    size: 'M',
    harborType: 'CN',
    unlocode: 'MTMLA',
    channelDepthFt: 16,
    rail: 'U',
  },
  {
    id: 'wpi:16950',
    name: 'Vancouver',
    country: 'US',
    lat: 45.6333,
    lon: -122.6833,
    size: 'M',
    harborType: 'RN',
    unlocode: 'USVAN',
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:18150',
    name: 'Vancouver',
    country: 'CA',
    lat: 49.2833,
    lon: -123.1167,
    size: 'L',
    harborType: 'CN',
    unlocode: 'CAVAN',
    channelDepthFt: 23,
    rail: 'Y',
  },
  {
    id: 'wpi:25395',
    name: 'Vasteras',
    country: 'SE',
    lat: 59.6167,
    lon: 16.55,
    size: 'M',
    harborType: 'LC',
    unlocode: 'SEVST',
    channelDepthFt: 5,
    rail: 'Y',
  },
  {
    id: 'wpi:18670',
    name: 'Victoria Harbor',
    country: 'CA',
    lat: 48.4333,
    lon: -123.3833,
    size: 'M',
    harborType: 'CB',
    unlocode: 'CAVIC',
    channelDepthFt: 17,
    rail: 'Y',
  },
  {
    id: 'wpi:37900',
    name: 'Vigo',
    country: 'ES',
    lat: 42.2333,
    lon: -8.7167,
    size: 'M',
    harborType: 'CB',
    unlocode: 'ESVGO',
    channelDepthFt: 23,
    rail: 'Y',
  },
  {
    id: 'wpi:12850',
    name: 'Vitoria',
    country: 'BR',
    lat: -20.3167,
    lon: -40.3333,
    size: 'M',
    harborType: 'RN',
    unlocode: 'BRVIX',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:60610',
    name: 'Vladivostok',
    country: 'RU',
    lat: 43.1089,
    lon: 131.8883,
    size: 'L',
    harborType: 'CN',
    unlocode: 'RUVVO',
    channelDepthFt: 19,
    rail: 'Y',
  },
  {
    id: 'wpi:31210',
    name: 'Vlissingen',
    country: 'NL',
    lat: 51.45,
    lon: 3.6,
    size: 'M',
    harborType: 'RN',
    unlocode: 'NLVLI',
    channelDepthFt: 13,
    rail: 'Y',
  },
  {
    id: 'wpi:42470',
    name: 'Volos',
    country: 'GR',
    lat: 39.3667,
    lon: 22.95,
    size: 'M',
    harborType: 'CB',
    unlocode: 'GRVOL',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:62120',
    name: 'Wakamatsu Ko',
    country: 'JP',
    lat: 33.9,
    lon: 130.8167,
    size: 'L',
    harborType: 'CN',
    unlocode: 'JPWAM',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:61545',
    name: 'Wakayama-Shimotsu Ko',
    country: 'JP',
    lat: 34.2,
    lon: 135.1333,
    size: 'L',
    harborType: 'CB',
    unlocode: 'JPWAK',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:60150',
    name: 'Weihai',
    country: 'CN',
    lat: 37.5,
    lon: 122.1,
    size: 'M',
    harborType: 'CN',
    unlocode: 'CNWEG',
    channelDepthFt: 23,
    rail: 'U',
  },
  {
    id: 'wpi:55150',
    name: 'Wellington',
    country: 'NZ',
    lat: -41.2833,
    lon: 174.7833,
    size: 'L',
    harborType: 'CN',
    unlocode: 'NZWLG',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:59910',
    name: 'Wenzhou',
    country: 'CN',
    lat: 28.0167,
    lon: 120.65,
    size: 'M',
    harborType: 'RN',
    unlocode: 'CNWZO',
    channelDepthFt: 3,
    rail: 'U',
  },
  {
    id: 'wpi:8470',
    name: 'Wilmington',
    country: 'US',
    lat: 34.2333,
    lon: -77.95,
    size: 'M',
    harborType: 'RN',
    unlocode: 'USILM',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:8050',
    name: 'Wilmington',
    country: 'US',
    lat: 39.7333,
    lon: -75.55,
    size: 'M',
    harborType: 'RN',
    unlocode: 'USILG',
    channelDepthFt: 6,
    rail: 'Y',
  },
  {
    id: 'wpi:3390',
    name: 'Windsor',
    country: 'CA',
    lat: 42.3167,
    lon: -83.0333,
    size: 'M',
    harborType: 'RN',
    unlocode: 'CAWND',
    channelDepthFt: 6,
    rail: 'Y',
  },
  {
    id: 'wpi:57870',
    name: 'Xiamen',
    country: 'CN',
    lat: 24.45,
    lon: 118.0667,
    size: 'M',
    harborType: 'RN',
    unlocode: 'CNXMG',
    channelDepthFt: 10,
    rail: 'Y',
  },
  {
    id: 'wpi:61490',
    name: 'Yokkaichi',
    country: 'JP',
    lat: 34.9667,
    lon: 136.6333,
    size: 'M',
    harborType: 'CB',
    unlocode: 'JPYKK',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:61390',
    name: 'Yokohama Ko',
    country: 'JP',
    lat: 35.45,
    lon: 139.5833,
    size: 'L',
    harborType: 'CB',
    unlocode: 'JPYOK',
    channelDepthFt: 11,
    rail: 'Y',
  },
  {
    id: 'wpi:61400',
    name: 'Yokosuka Ko',
    country: 'JP',
    lat: 35.2833,
    lon: 139.6667,
    size: 'M',
    harborType: 'CN',
    unlocode: 'JPYOS',
    channelDepthFt: 14,
    rail: 'Y',
  },
  {
    id: 'wpi:31280',
    name: 'Zeebrugge',
    country: 'BE',
    lat: 51.3333,
    lon: 3.2,
    size: 'M',
    harborType: 'CB',
    unlocode: 'BEZEE',
    channelDepthFt: 9,
    rail: 'Y',
  },
  {
    id: 'wpi:48266',
    name: 'Zirkuh',
    country: 'AE',
    lat: 25.0167,
    lon: 53,
    size: 'M',
    harborType: 'OR',
    unlocode: 'AEZUR',
    channelDepthFt: 20,
    rail: 'U',
  },
]);
