/**
 * Generate the bundled country-border polylines.
 *
 *   node scripts/build-borders.mjs
 *
 * Writes src/supplychain/reference/borders.js.
 *
 * WHY THIS EXISTS: a 3D globe without borders makes geography guesswork. The
 * user cannot tell which country they are looking at, which country a port
 * belongs to, or whether a route crosses a frontier — and every one of those is
 * a supply-chain question.
 *
 * Natural Earth 110m is used here rather than the 50m the label anchors come
 * from. Borders are decoration for orientation, not a basis for any claim, and
 * 110m is roughly a quarter the size. Microstates that 110m omits still get
 * their label anchor from countries.js, so nothing disappears from the app —
 * only its outline is absent, which at global zoom is invisible anyway.
 *
 * Coordinates are rounded to 2 decimal places (~1 km at the equator) and rings
 * shorter than a few points are dropped. Both are lossy on purpose: this is an
 * orientation aid, and a border drawn to survey precision would cost megabytes
 * to say the same thing.
 *
 * DISPUTED BOUNDARIES: Natural Earth's admin-0 boundaries follow its own
 * editorial decisions, which do not match every government's position. The
 * generated file says so, and the layer's provenance repeats it. This project
 * takes no position on any territorial dispute; it draws an orientation aid.
 */

import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const SOURCE =
  'https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_admin_0_countries.geojson';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'src', 'supplychain', 'reference', 'borders.js');

/** Decimal places kept. 2 is ~1.1 km at the equator. */
const PRECISION = 2;
/** Rings with fewer points than this are noise at global zoom. */
const MIN_RING_POINTS = 4;

const round = (n) => Number(Number(n).toFixed(PRECISION));

/** Drop consecutive duplicate points left behind by rounding. */
function simplify(ring) {
  const out = [];
  let lastLon = null;
  let lastLat = null;
  for (const [lon, lat] of ring) {
    const rLon = round(lon);
    const rLat = round(lat);
    if (rLon === lastLon && rLat === lastLat) continue;
    out.push(rLon, rLat);
    lastLon = rLon;
    lastLat = rLat;
  }
  return out;
}

function ringsOf(geometry) {
  if (!geometry) return [];
  if (geometry.type === 'Polygon') return geometry.coordinates;
  if (geometry.type === 'MultiPolygon') return geometry.coordinates.flat();
  return [];
}

const response = await fetch(SOURCE);
if (!response.ok) throw new Error(`${SOURCE}: HTTP ${response.status}`);
const collection = await response.json();

const countries = [];
let totalPoints = 0;
let droppedRings = 0;

for (const feature of collection.features) {
  const p = feature.properties;
  const direct = p.ISO_A3 && p.ISO_A3 !== '-99';
  const iso3 = direct ? p.ISO_A3 : (p.ISO_A3_EH ?? p.ADM0_A3);
  if (!iso3 || iso3 === '-99') continue;

  const rings = [];
  for (const ring of ringsOf(feature.geometry)) {
    const flat = simplify(ring);
    if (flat.length / 2 < MIN_RING_POINTS) {
      droppedRings += 1;
      continue;
    }
    rings.push(flat);
    totalPoints += flat.length / 2;
  }
  if (!rings.length) continue;
  countries.push({ iso3, name: p.NAME ?? iso3, rings });
}

countries.sort((a, b) => a.iso3.localeCompare(b.iso3));

const quote = (value) =>
  `'${String(value).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

const body = countries
  .map(
    (country) =>
      `  Object.freeze({\n` +
      `    iso3: ${quote(country.iso3)},\n` +
      `    name: ${quote(country.name)},\n` +
      `    rings: Object.freeze([\n` +
      country.rings
        .map((ring) => `      Object.freeze([${ring.join(',')}]),`)
        .join('\n') +
      `\n    ]),\n` +
      `  }),`,
  )
  .join('\n');

const file = `/**
 * Country border outlines, for orientation on the globe.
 *
 * GENERATED by scripts/build-borders.mjs. Do not edit by hand.
 *
 * Source: Natural Earth 110m admin-0 countries (public domain).
 * Generated: ${new Date().toISOString().slice(0, 10)}
 * ${countries.length} countries, ${totalPoints.toLocaleString()} points, rounded to ${PRECISION} decimal places.
 *
 * Each ring is a FLAT array [lon, lat, lon, lat, ...] rather than an array of
 * pairs: it halves the object count for the same data, which matters when the
 * renderer walks every point each frame.
 *
 * ORIENTATION AID, NOT AN AUTHORITY. Coordinates are rounded to about a
 * kilometre and small islands are dropped. Natural Earth's admin-0 boundaries
 * follow its own editorial decisions, which do not match every government's
 * position on every frontier. This project takes no position on any territorial
 * dispute and nothing here should be read as one.
 *
 * Portable: no Cesium, no Node, no browser globals.
 */

export const BORDER_SOURCE = 'Natural Earth 110m admin-0 (public domain)';

export const BORDER_CAVEAT =
  'Country outlines are an orientation aid, simplified to about 1 km and ' +
  'following Natural Earth\\u2019s editorial boundary decisions. They are not ' +
  'an authority on any frontier, and this project takes no position on any ' +
  'territorial dispute.';

/** @type {ReadonlyArray<{iso3:string,name:string,rings:ReadonlyArray<ReadonlyArray<number>>}>} */
export const COUNTRY_BORDERS = Object.freeze([
${body}
]);

/** Borders for one ISO3 code, or null. */
export function borderFor(iso3) {
  return COUNTRY_BORDERS.find((entry) => entry.iso3 === iso3) ?? null;
}
`;

writeFileSync(OUT, file);
console.log(
  `borders: ${countries.length} countries, ${totalPoints.toLocaleString()} points, ` +
    `${droppedRings} tiny rings dropped, ${(file.length / 1024).toFixed(0)} KB`,
);
